<?php

/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

declare(strict_types=1);

namespace Apollo\Deploy\Signal\Sdk;

use DateTimeImmutable;
use DateTimeInterface;
use BackedEnum;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Uri;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamInterface;
use Throwable;

final class SSEEvent
{
    public function __construct(
        public readonly string $type,
        public readonly mixed $data,
        public readonly ?string $id = null,
        public readonly ?int $retryMilliseconds = null,
    ) {
    }
}

class Transport
{
    public const MAX_RESPONSE_BODY_BYTES = 5 * 1024 * 1024;
    public const MAX_SSE_LINE_BYTES = 1024 * 1024;

    private const MAX_RETRIES = 8;
    private const MAX_RETRY_DELAY_MS = 30000;
    private const RETRYABLE_METHODS = ['GET', 'HEAD', 'OPTIONS', 'PUT', 'DELETE'];
    private const RETRYABLE_STATUSES = [408, 425, 429, 500, 502, 503, 504];

    private ClientInterface $http;

    /** @var array<string, mixed> */
    private array $config;

    /** @var list<array{0: string, 1: string}> */
    private array $baseQueryPairs;

    public static function wireValue(mixed $value): string
    {
        if ($value instanceof BackedEnum) {
            $value = $value->value;
        }
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }
        if ($value instanceof DateTimeInterface) {
            return $value->format(DATE_ATOM);
        }
        if (is_string($value) || is_int($value) || is_float($value)) {
            return (string) $value;
        }
        if ($value instanceof \Stringable) {
            return (string) $value;
        }
        throw new \InvalidArgumentException('Wire parameter values must be scalar, enum, date/time, or stringable');
    }

    /**
     * @param array{
     *     baseUrl?: string,
     *     timeoutMs?: int,
     *     retries?: array{attempts?: int, backoffMs?: int, jitter?: bool, maxBackoffMs?: int},
     *     retryUnsafeRequests?: bool,
     *     defaultHeaders?: array<string, string>,
     * } $config
     */
    public function __construct(array $config = [])
    {
        $timeoutMs = (int) ($config['timeoutMs'] ?? 15000);
        if ($timeoutMs <= 0) {
            throw new \InvalidArgumentException('timeoutMs must be greater than zero');
        }

        $this->config = $config;
        $baseUrl = (string) ($config['baseUrl'] ?? 'https://signal.apollodeploy.com');
        $baseUri = new Uri($baseUrl);
        if (!in_array(strtolower($baseUri->getScheme()), ['http', 'https'], true) || $baseUri->getHost() === '') {
            throw new \InvalidArgumentException('baseUrl must be an absolute HTTP(S) URL');
        }
        $this->baseQueryPairs = self::parseQueryPairs($baseUri->getQuery());
        $basePath = rtrim($baseUri->getPath(), '/');
        $baseUri = $baseUri
            ->withPath($basePath === '' ? '/' : $basePath . '/')
            ->withQuery('')
            ->withFragment('');
        $headers = $config['defaultHeaders'] ?? [];
        $headers['Accept'] = $headers['Accept'] ?? 'application/json';
        $headers['User-Agent'] = $headers['User-Agent'] ?? 'ApolloSignalApi-php-sdk/1.0.5';

        $this->http = new GuzzleClient([
            'base_uri' => (string) $baseUri,
            'timeout' => $timeoutMs / 1000.0,
            'http_errors' => false,
            'headers' => $headers,
        ]);
    }

    /**
     * @param array{
     *     method: string,
     *     path: string,
     *     query?: array<string, mixed>,
     *     body?: mixed,
     *     headers?: array<string, string>,
     *     contentType?: string,
     *     timeoutMs?: int,
     *     retries?: int,
     *     retryUnsafeRequests?: bool,
     *     stream?: bool,
     * } $requestDef
     * @throws SDKError
     */
    public function executeRequest(array $requestDef): ResponseInterface
    {
        $method = strtoupper((string) $requestDef['method']);
        $path = ltrim((string) $requestDef['path'], '/');
        $query = $this->buildQueryString(
            $requestDef['query'] ?? [],
            $this->buildAuthQuery(),
        );
        $body = $requestDef['body'] ?? null;
        $headers = array_merge($requestDef['headers'] ?? [], $this->buildAuthHeaders());
        $headers = $this->appendAuthCookies($headers);
        $contentType = (string) ($requestDef['contentType'] ?? 'application/json');
        $isStream = ($requestDef['stream'] ?? false) === true;
        if ($isStream) {
            foreach (array_keys($headers) as $headerName) {
                if (strcasecmp((string) $headerName, 'Accept') === 0) {
                    unset($headers[$headerName]);
                }
            }
            $headers['Accept'] = 'text/event-stream';
        }

        $options = [RequestOptions::HEADERS => $headers];
        if ($query !== '') {
            $options[RequestOptions::QUERY] = $query;
        }
        if ($body !== null) {
            $mediaType = strtolower(trim(explode(';', $contentType, 2)[0]));
            $isJson = $mediaType === 'application/json' || str_ends_with($mediaType, '+json');
            if ($isJson) {
                $options[RequestOptions::JSON] = $body;
                $options[RequestOptions::HEADERS]['Content-Type'] = $contentType;
            } elseif ($mediaType === 'multipart/form-data') {
                $options[RequestOptions::MULTIPART] = $this->buildMultipartParts($body);
            } else {
                $options[RequestOptions::BODY] = $body;
                $options[RequestOptions::HEADERS]['Content-Type'] = $contentType;
            }
        }
        if ($isStream) {
            $options[RequestOptions::STREAM] = true;
        }
        if (isset($requestDef['timeoutMs'])) {
            $timeoutMs = (int) $requestDef['timeoutMs'];
            if ($timeoutMs <= 0) {
                throw new \InvalidArgumentException('timeoutMs must be greater than zero');
            }
            $options[RequestOptions::TIMEOUT] = $timeoutMs / 1000.0;
        }

        $retryConfig = $this->config['retries'] ?? [];
        $maxRetries = min(
            self::MAX_RETRIES,
            max(0, (int) ($requestDef['retries'] ?? $retryConfig['attempts'] ?? 3)),
        );
        $retryUnsafe = (bool) (
            $requestDef['retryUnsafeRequests']
            ?? $this->config['retryUnsafeRequests']
            ?? false
        );

        return $this->executeWithRetry(
            $method,
            $path,
            $options,
            $maxRetries,
            $retryUnsafe,
        );
    }

    /** @return list<array{name: string, contents: mixed, filename?: string, headers?: array<string, string>}> */
    private function buildMultipartParts(mixed $body): array
    {
        $normalized = $this->normalizeMultipartValue($body);
        if (!is_array($normalized)) {
            throw new \InvalidArgumentException(
                'Multipart request bodies must be arrays or objects with toArray()',
            );
        }

        $parts = [];
        foreach ($normalized as $name => $value) {
            $this->appendMultipartParts($parts, (string) $name, $value);
        }
        return $parts;
    }

    private function normalizeMultipartValue(mixed $value): mixed
    {
        if (is_object($value) && method_exists($value, 'toArray')) {
            return $this->normalizeMultipartValue($value->toArray());
        }
        if ($value instanceof \Traversable) {
            return $this->normalizeMultipartValue(iterator_to_array($value));
        }
        return $value;
    }

    /** @param list<array{name: string, contents: mixed, filename?: string, headers?: array<string, string>}> $parts */
    private function appendMultipartParts(array &$parts, string $name, mixed $value): void
    {
        $value = $this->normalizeMultipartValue($value);
        if ($value === null) {
            return;
        }

        if (is_array($value) && $this->isMultipartDescriptor($value)) {
            $part = [
                'name' => (string) ($value['name'] ?? $name),
                'contents' => $value['contents'],
            ];
            if (isset($value['filename']) && $value['filename'] !== '') {
                $part['filename'] = (string) $value['filename'];
            }
            $partHeaders = isset($value['headers']) && is_array($value['headers'])
                ? $value['headers']
                : [];
            $contentType = $value['content_type'] ?? $value['contentType'] ?? null;
            if ($contentType !== null) {
                $partHeaders['Content-Type'] = (string) $contentType;
            }
            if ($partHeaders !== []) {
                $part['headers'] = array_map(
                    static fn (mixed $headerValue): string => (string) $headerValue,
                    $partHeaders,
                );
            }
            $parts[] = $part;
            return;
        }

        if (is_array($value)) {
            if (array_is_list($value)) {
                foreach ($value as $item) {
                    $this->appendMultipartParts($parts, $name, $item);
                }
                return;
            }

            foreach ($value as $nestedName => $nestedValue) {
                $this->appendMultipartParts(
                    $parts,
                    $name . '[' . (string) $nestedName . ']',
                    $nestedValue,
                );
            }
            return;
        }

        if (is_resource($value) || $value instanceof StreamInterface) {
            $parts[] = ['name' => $name, 'contents' => $value];
            return;
        }

        if (is_string($value) || is_int($value) || is_float($value) || is_bool($value)) {
            $parts[] = [
                'name' => $name,
                'contents' => is_bool($value) ? ($value ? 'true' : 'false') : (string) $value,
            ];
            return;
        }

        if (is_object($value) && method_exists($value, '__toString')) {
            $parts[] = ['name' => $name, 'contents' => (string) $value];
            return;
        }

        throw new \InvalidArgumentException(
            'Multipart field values must be scalar values, arrays, or readable streams',
        );
    }

    /** @param array<mixed> $value */
    private function isMultipartDescriptor(array $value): bool
    {
        if (!array_key_exists('contents', $value)) {
            return false;
        }

        $allowedKeys = ['name', 'contents', 'filename', 'headers', 'content_type', 'contentType'];
        return array_diff(array_keys($value), $allowedKeys) === [];
    }

    /** @return \Generator<int, SSEEvent> */
    public function streamEvents(ResponseInterface $response): \Generator
    {
        $body = $response->getBody();
        $buffer = '';
        $dataLines = [];
        $eventType = 'message';
        $eventId = null;
        $retryMilliseconds = null;
        $totalBytes = 0;

        $flush = static function () use (&$dataLines, &$eventType, &$eventId, &$retryMilliseconds): ?SSEEvent {
            if ($dataLines === []) {
                $eventType = 'message';
                $eventId = null;
                $retryMilliseconds = null;
                return null;
            }

            $rawData = implode("\n", $dataLines);
            try {
                $data = json_decode($rawData, true, 512, JSON_THROW_ON_ERROR);
            } catch (\JsonException) {
                $data = $rawData;
            }
            $event = new SSEEvent(
                type: $eventType,
                data: $data,
                id: $eventId,
                retryMilliseconds: $retryMilliseconds,
            );
            $dataLines = [];
            $eventType = 'message';
            $eventId = null;
            $retryMilliseconds = null;
            return $event;
        };

        $pending = null;
        $processLine = static function (string $line) use (
            &$pending,
            &$dataLines,
            &$eventType,
            &$eventId,
            &$retryMilliseconds,
            $flush,
        ): void {
            $line = rtrim($line, "\r");
            if (strlen($line) > self::MAX_SSE_LINE_BYTES) {
                throw new SDKError(
                    message: 'SSE line exceeded the configured safety limit',
                    code: 'SSE_LINE_TOO_LARGE',
                );
            }
            if ($line === '') {
                $pending = $flush();
                return;
            }
            if (str_starts_with($line, ':')) {
                return;
            }

            $separator = strpos($line, ':');
            $field = $separator === false ? $line : substr($line, 0, $separator);
            $value = $separator === false ? '' : substr($line, $separator + 1);
            if ($value !== '' && $value[0] === ' ') {
                $value = substr($value, 1);
            }
            switch ($field) {
                case 'event':
                    $eventType = $value;
                    break;
                case 'data':
                    $dataLines[] = $value;
                    break;
                case 'id':
                    if (!str_contains($value, "\0")) {
                        $eventId = $value;
                    }
                    break;
                case 'retry':
                    if (preg_match('/^\d+$/', $value) === 1) {
                        $retryMilliseconds = (int) $value;
                    }
                    break;
            }
        };

        while (!$body->eof()) {
            $chunk = $body->read(8192);
            if ($chunk === '') {
                break;
            }
            $totalBytes += strlen($chunk);
            if ($totalBytes > self::MAX_RESPONSE_BODY_BYTES) {
                throw new SDKError(
                    message: 'Response body exceeded the configured safety limit',
                    code: 'RESPONSE_BODY_TOO_LARGE',
                );
            }
            $buffer .= $chunk;
            while (($lineEnd = strpos($buffer, "\n")) !== false) {
                $line = substr($buffer, 0, $lineEnd);
                $buffer = substr($buffer, $lineEnd + 1);
                $processLine($line);
                if ($pending !== null) {
                    $event = $pending;
                    $pending = null;
                    yield $event;
                }
            }
            if (strlen($buffer) > self::MAX_SSE_LINE_BYTES) {
                throw new SDKError(
                    message: 'SSE line exceeded the configured safety limit',
                    code: 'SSE_LINE_TOO_LARGE',
                );
            }
        }

        if ($buffer !== '') {
            $processLine($buffer);
            if ($pending !== null) {
                $event = $pending;
                $pending = null;
                yield $event;
            }
        }
        $pending = $flush();
        if ($pending !== null) {
            yield $pending;
        }
    }

    /** @throws SDKError */
    private function executeWithRetry(
        string $method,
        string $path,
        array $options,
        int $maxRetries,
        bool $retryUnsafe,
    ): ResponseInterface {
        $retryConfig = $this->config['retries'] ?? [];
        $baseBackoffMs = max(0, (int) ($retryConfig['backoffMs'] ?? 400));
        $useJitter = (bool) ($retryConfig['jitter'] ?? true);
        $maxBackoffMs = min(
            self::MAX_RETRY_DELAY_MS,
            max(0, (int) ($retryConfig['maxBackoffMs'] ?? self::MAX_RETRY_DELAY_MS)),
        );
        $canRetry = $this->canRetryMethod($method, $options[RequestOptions::HEADERS] ?? [], $retryUnsafe);
        $lastError = null;

        for ($attempt = 0; $attempt <= $maxRetries; $attempt++) {
            try {
                $request = new Request($method, $path, $options[RequestOptions::HEADERS] ?? []);
                $response = $this->http->send($request, $options);
                $status = $response->getStatusCode();

                if ($status >= 200 && $status < 300) {
                    return $response;
                }

                $lastError = $this->errorFromResponse($response);
                if (!$canRetry || !in_array($status, self::RETRYABLE_STATUSES, true) || $attempt >= $maxRetries) {
                    throw $lastError;
                }

                $this->sleep($this->retryDelayMs(
                    $response->getHeaderLine('Retry-After'),
                    $attempt,
                    $baseBackoffMs,
                    $useJitter,
                    $maxBackoffMs,
                ));
            } catch (ConnectException $exception) {
                $lastError = SDKError::fromException($exception);
                if (!$canRetry || $attempt >= $maxRetries) {
                    throw $lastError;
                }
                $this->sleep($this->retryDelayMs(
                    null,
                    $attempt,
                    $baseBackoffMs,
                    $useJitter,
                    $maxBackoffMs,
                ));
            } catch (RequestException $exception) {
                $response = $exception->getResponse();
                $lastError = $response === null
                    ? SDKError::fromException($exception)
                    : $this->errorFromResponse($response, $exception);
                if (
                    !$canRetry
                    || $attempt >= $maxRetries
                    || ($response !== null && !in_array($response->getStatusCode(), self::RETRYABLE_STATUSES, true))
                ) {
                    throw $lastError;
                }
                $this->sleep($this->retryDelayMs(
                    $response?->getHeaderLine('Retry-After'),
                    $attempt,
                    $baseBackoffMs,
                    $useJitter,
                    $maxBackoffMs,
                ));
            }
        }

        throw $lastError ?? new SDKError('Request failed after retries', 0, 'RETRY_EXHAUSTED');
    }

    /** @param array<string, string> $headers */
    private function canRetryMethod(string $method, array $headers, bool $retryUnsafe): bool
    {
        if ($retryUnsafe || in_array($method, self::RETRYABLE_METHODS, true)) {
            return true;
        }
        $effectiveHeaders = array_merge($this->config['defaultHeaders'] ?? [], $headers);
        foreach ($effectiveHeaders as $name => $value) {
            if (
                in_array(strtolower((string) $name), ['idempotency-key', 'x-idempotency-key'], true)
                && $value !== ''
            ) {
                return true;
            }
        }
        return false;
    }

    private function retryDelayMs(
        ?string $retryAfter,
        int $attempt,
        int $baseMs,
        bool $jitter,
        int $maxMs,
    ): int {
        $retryAfterMs = $this->parseRetryAfterMs($retryAfter);
        if ($retryAfterMs !== null) {
            return min($retryAfterMs, $maxMs);
        }

        $cap = min($baseMs * (2 ** $attempt), $maxMs);
        return $jitter ? random_int(0, max(0, $cap)) : $cap;
    }

    private function parseRetryAfterMs(?string $value): ?int
    {
        if ($value === null || trim($value) === '') {
            return null;
        }
        if (is_numeric($value)) {
            return max(0, (int) ceil((float) $value * 1000));
        }
        try {
            $time = new DateTimeImmutable($value);
            return max(0, ($time->getTimestamp() - time()) * 1000);
        } catch (Throwable) {
            return null;
        }
    }

    /** @return array<string, string> */
    private function buildAuthHeaders(): array
    {
        $headers = [];
        $claimedSecurityHeaders = [];
        return $headers;
    }

    /**
     * @param array<string, string> $headers
     * @param array<string, true> $claimedHeaders
     */
    private function setSecurityHeader(
        array &$headers,
        array &$claimedHeaders,
        string $name,
        string $value,
    ): void {
        $normalized = strtolower($name);
        if (array_key_exists($normalized, $claimedHeaders)) {
            throw new \InvalidArgumentException(
                "Multiple configured security schemes target the {$name} header",
            );
        }
        $claimedHeaders[$normalized] = true;
        $headers[$name] = $value;
    }

    /** @return array<string, string> */
    private function buildAuthQuery(): array
    {
        $query = [];
        return $query;
    }

    /**
     * @param array<string, mixed> $requestQuery
     * @param array<string, string> $authQuery
     */
    private function buildQueryString(array $requestQuery, array $authQuery): string
    {
        $requestPairs = self::queryPairs($requestQuery);
        $requestNames = array_fill_keys(array_column($requestPairs, 0), true);
        $pairs = array_values(array_filter(
            $this->baseQueryPairs,
            static fn (array $pair): bool => !array_key_exists($pair[0], $requestNames),
        ));
        array_push($pairs, ...$requestPairs);

        if ($authQuery !== []) {
            $authNames = array_fill_keys(array_keys($authQuery), true);
            $pairs = array_values(array_filter(
                $pairs,
                static fn (array $pair): bool => !array_key_exists($pair[0], $authNames),
            ));
            array_push($pairs, ...self::queryPairs($authQuery));
        }

        return implode('&', array_map(
            static fn (array $pair): string => rawurlencode($pair[0]) . '=' . rawurlencode($pair[1]),
            $pairs,
        ));
    }

    /** @param array<string, mixed> $query @return list<array{0: string, 1: string}> */
    private static function queryPairs(array $query): array
    {
        $pairs = [];
        foreach ($query as $name => $value) {
            if ($value === null) {
                continue;
            }
            $values = is_array($value) ? $value : [$value];
            foreach ($values as $item) {
                if ($item !== null) {
                    $pairs[] = [(string) $name, self::wireValue($item)];
                }
            }
        }
        return $pairs;
    }

    /** @return list<array{0: string, 1: string}> */
    private static function parseQueryPairs(string $query): array
    {
        if ($query === '') {
            return [];
        }
        $pairs = [];
        foreach (explode('&', $query) as $segment) {
            [$name, $value] = array_pad(explode('=', $segment, 2), 2, '');
            $pairs[] = [urldecode($name), urldecode($value)];
        }
        return $pairs;
    }

    /** @return array<string, string> */
    private function buildAuthCookies(): array
    {
        $cookies = [];
        return $cookies;
    }

    private function configuredCredential(string $key): ?string
    {
        $value = $this->config[$key] ?? null;
        if ($value === null || $value === '') {
            return null;
        }
        if (!is_string($value)) {
            throw new \InvalidArgumentException("Credential {$key} must be a string");
        }
        return $value;
    }

    /** @param array<string, string> $headers */
    private function appendAuthCookies(array $headers): array
    {
        $cookies = $this->buildAuthCookies();
        if ($cookies === []) {
            return $headers;
        }

        $serialized = implode('; ', array_map(
            static fn (string $name, string $value): string =>
                rawurlencode($name) . '=' . rawurlencode($value),
            array_keys($cookies),
            array_values($cookies),
        ));
        foreach ($headers as $name => $value) {
            if (strcasecmp((string) $name, 'Cookie') === 0) {
                $existing = [];
                foreach (explode(';', $value) as $segment) {
                    $segment = trim($segment);
                    if ($segment === '') {
                        continue;
                    }
                    $separator = strpos($segment, '=');
                    $cookieName = trim($separator === false ? $segment : substr($segment, 0, $separator));
                    if (
                        array_key_exists($cookieName, $cookies)
                        || array_key_exists(rawurldecode($cookieName), $cookies)
                    ) {
                        continue;
                    }
                    $existing[] = $segment;
                }
                $headers[$name] = implode('; ', array_merge($existing, [$serialized]));
                return $headers;
            }
        }

        $headers['Cookie'] = $serialized;
        return $headers;
    }

    /** @throws SDKError */
    public function readResponseBody(ResponseInterface $response): string
    {
        return $this->readBody($response->getBody(), self::MAX_RESPONSE_BODY_BYTES);
    }

    /** @throws SDKError */
    private function readBody(StreamInterface $body, int $maximumBytes): string
    {
        $contents = '';
        while (!$body->eof()) {
            $chunk = $body->read(min(8192, $maximumBytes + 1 - strlen($contents)));
            if ($chunk === '') {
                break;
            }
            $contents .= $chunk;
            if (strlen($contents) > $maximumBytes) {
                throw new SDKError(
                    message: 'Response body exceeded the configured safety limit',
                    code: 'RESPONSE_BODY_TOO_LARGE',
                );
            }
        }
        return $contents;
    }

    private function sleep(int $milliseconds): void
    {
        if ($milliseconds > 0) {
            usleep($milliseconds * 1000);
        }
    }

    private function errorFromResponse(
        ResponseInterface $response,
        ?Throwable $previous = null,
    ): SDKError {
        $body = $this->decodeResponseBody($response);
        $nested = is_array($body['error'] ?? null) ? $body['error'] : [];
        $message = $body['message'] ?? $nested['message'] ?? null;
        if ($message === null && is_string($body['error'] ?? null)) {
            $message = $body['error'];
        }
        $message ??= trim((string) ($body['raw'] ?? ''));
        $code = $body['code'] ?? $body['error_code'] ?? $nested['code'] ?? null;
        if ($code === null && is_string($body['error'] ?? null)) {
            $code = $body['error'];
        }
        $requestId = $body['request_id']
            ?? $response->getHeaderLine('x-request-id')
            ?: $response->getHeaderLine('request-id')
            ?: null;

        return new SDKError(
            message: (string) ($message ?: 'HTTP ' . $response->getStatusCode()),
            status: $response->getStatusCode(),
            code: (string) ($code ?: 'HTTP_ERROR'),
            requestId: $requestId,
            responseBody: $body,
            previous: $previous,
        );
    }

    /** @return array<string, mixed> */
    private function decodeResponseBody(ResponseInterface $response): array
    {
        $contents = $this->readResponseBody($response);
        try {
            $decoded = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
            return is_array($decoded) ? $decoded : ['raw' => $decoded];
        } catch (Throwable) {
            return ['raw' => $contents];
        }
    }
}
