#!/usr/bin/env node
/** @generated by Tesseract. */

import { createApolloSignalApiClient } from '../index.js';

const MAX_JSON_INPUT_BYTES = 1024 * 1024;

type JsonObject = Record<string, unknown>;

interface CliArguments {
  command?: string;
  baseUrl?: string;
  timeoutMs?: number;
  body?: unknown;
  query?: JsonObject;
  headers?: JsonObject;
  cookies?: JsonObject;
  path: Record<string, string>;
  help: boolean;
}

function takeValue(argv: string[], index: number, flag: string): string {
  const value = argv[index + 1];
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
}

function parseJson(value: string, label: string): unknown {
  if (Buffer.byteLength(value, 'utf8') > MAX_JSON_INPUT_BYTES) {
    throw new Error(`${label} exceeds the 1 MiB input limit`);
  }
  try {
    return JSON.parse(value) as unknown;
  } catch {
    throw new Error(`${label} must be valid JSON`);
  }
}

function parseObject(value: string, label: string): JsonObject {
  const parsed = parseJson(value, label);
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error(`${label} must be a JSON object`);
  }
  return parsed as JsonObject;
}

function parsePositiveInteger(value: string, label: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) {
    throw new Error(`${label} must be a positive integer`);
  }
  return parsed;
}

function parseCommandLine(argv: string[]): CliArguments {
  const result: CliArguments = {
    path: Object.create(null) as Record<string, string>,
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith('--')) {
      if (result.command !== undefined) {
        throw new Error(`Unexpected positional argument: ${token}`);
      }
      result.command = token;
      continue;
    }

    switch (token) {
      case '--help':
        result.help = true;
        break;
      case '--base-url':
        result.baseUrl = takeValue(argv, index, token);
        index += 1;
        break;
      case '--timeout-ms':
        result.timeoutMs = parsePositiveInteger(takeValue(argv, index, token), token);
        index += 1;
        break;
      case '--body-json':
        result.body = parseJson(takeValue(argv, index, token), token);
        index += 1;
        break;
      case '--query-json':
        result.query = parseObject(takeValue(argv, index, token), token);
        index += 1;
        break;
      case '--headers-json':
        result.headers = parseObject(takeValue(argv, index, token), token);
        index += 1;
        break;
      case '--cookies-json':
        result.cookies = parseObject(takeValue(argv, index, token), token);
        index += 1;
        break;
      case '--path': {
        const pair = takeValue(argv, index, token);
        const separator = pair.indexOf('=');
        if (separator <= 0) throw new Error('--path must use name=value');
        result.path[pair.slice(0, separator)] = pair.slice(separator + 1);
        index += 1;
        break;
      }
      default:
        throw new Error(`Unknown option: ${token}`);
    }
  }
  return result;
}

function requirePath(path: Record<string, string>, name: string): string {
  const value = path[name];
  if (value === undefined) throw new Error(`Missing required --path ${name}=...`);
  return value;
}

function requireValue(value: unknown, label: string): unknown {
  if (value === undefined) throw new Error(`Missing required ${label}`);
  return value;
}

function requireObject(value: JsonObject | undefined, label: string): JsonObject {
  if (value === undefined) throw new Error(`Missing required ${label}`);
  return value;
}

function requireField(value: JsonObject, name: string, label: string): void {
  if (value[name] === undefined || value[name] === null) {
    throw new Error(`Missing required ${label} field: ${name}`);
  }
}

function parsePathValue(value: string, type: string): unknown {
  const normalized = type.replaceAll(' ', '');
  if (normalized === 'integer') {
    const parsed = Number(value);
    if (!Number.isSafeInteger(parsed))
      throw new Error(`Expected integer path value, received ${value}`);
    return parsed;
  }
  if (normalized === 'number') {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) throw new Error(`Expected numeric path value, received ${value}`);
    return parsed;
  }
  if (normalized === 'boolean') {
    if (value === 'true') return true;
    if (value === 'false') return false;
    throw new Error(`Expected boolean path value, received ${value}`);
  }
  return value;
}

function isAsyncIterable(value: unknown): value is AsyncIterable<unknown> {
  return Boolean(
    value &&
    typeof value === 'object' &&
    Symbol.asyncIterator in value &&
    typeof (value as AsyncIterable<unknown>)[Symbol.asyncIterator] === 'function',
  );
}

function printJson(value: unknown): void {
  process.stdout.write(`${JSON.stringify(value === undefined ? null : value)}\n`);
}

function printHelp(): void {
  process.stdout.write(`signal-cli <command> [options]\n\nCommands:\n`);
  process.stdout.write('  emails.send-email  POST /v1/emails\n');
  process.stdout.write('  emails.get-email  GET /v1/emails/${emailId}\n');
  process.stdout.write('  emails.batch-send-emails  POST /v1/emails/batch\n');
  process.stdout.write('  emails.cancel-email  DELETE /v1/emails/${emailId}\n');
  process.stdout.write('  emails.bulk-cancel-emails  DELETE /v1/emails\n');
  process.stdout.write('  emails.issue-stream-token  POST /v1/emails/${projectId}/stream/token\n');
  process.stdout.write('  emails.stream-email-events  GET /v1/emails/stream\n');
  process.stdout.write('  emails.validate-links  POST /v1/emails/validate\n');
  process.stdout.write('  metrics.get-topic-performance  GET /v1/metrics/topics/${id}\n');
  process.stdout.write('  metrics.get-email-performance  GET /v1/metrics/emails/${id}\n');
  process.stdout.write('  metrics.get-email-engagement  GET /v1/metrics/emails/${id}/engagement\n');
  process.stdout.write('  metrics.get-project-metrics-summary  GET /v1/metrics/summary\n');
  process.stdout.write('  metrics.get-project-metrics-timeline  GET /v1/metrics/timeline\n');
  process.stdout.write('  metrics.get-metrics-advisor  GET /v1/metrics/advisor\n');
  process.stdout.write(
    '  suppressions.list-suppressions  GET /v1/projects/${projectId}/suppressions\n',
  );
  process.stdout.write(
    '  suppressions.export-suppressions  GET /v1/projects/${projectId}/suppressions/export\n',
  );
  process.stdout.write(
    '  suppressions.add-suppression  POST /v1/projects/${projectId}/suppressions\n',
  );
  process.stdout.write(
    '  suppressions.remove-suppression  DELETE /v1/projects/${projectId}/suppressions/${email}\n',
  );
  process.stdout.write(
    '  suppressions.import-suppressions  POST /v1/projects/${projectId}/suppressions/import\n',
  );
  process.stdout.write('  segments.list-segments  GET /v1/projects/${projectId}/segments\n');
  process.stdout.write(
    '  segments.get-segment  GET /v1/projects/${projectId}/segments/${segmentId}\n',
  );
  process.stdout.write(
    '  segments.list-contacts-in-segment  GET /v1/projects/${projectId}/segments/${segmentId}/contacts\n',
  );
  process.stdout.write('  segments.create-segment  POST /v1/projects/${projectId}/segments\n');
  process.stdout.write(
    '  segments.delete-segment  DELETE /v1/projects/${projectId}/segments/${segmentId}\n',
  );
  process.stdout.write('  topics.list-topics  GET /v1/projects/${projectId}/topics\n');
  process.stdout.write('  topics.get-topic  GET /v1/projects/${projectId}/topics/${topicId}\n');
  process.stdout.write(
    '  topics.list-contacts-in-topic  GET /v1/projects/${projectId}/topics/${topicId}/contacts\n',
  );
  process.stdout.write('  topics.create-topic  POST /v1/projects/${projectId}/topics\n');
  process.stdout.write(
    '  topics.update-topic  PATCH /v1/projects/${projectId}/topics/${topicId}\n',
  );
  process.stdout.write(
    '  topics.delete-topic  DELETE /v1/projects/${projectId}/topics/${topicId}\n',
  );
  process.stdout.write(
    '  contact-properties.list-contact-properties  GET /v1/projects/${projectId}/contact-properties\n',
  );
  process.stdout.write(
    '  contact-properties.get-contact-property  GET /v1/projects/${projectId}/contact-properties/${propertyId}\n',
  );
  process.stdout.write(
    '  contact-properties.create-contact-property  POST /v1/projects/${projectId}/contact-properties\n',
  );
  process.stdout.write(
    '  contact-properties.update-contact-property  PATCH /v1/projects/${projectId}/contact-properties/${propertyId}\n',
  );
  process.stdout.write(
    '  contact-properties.delete-contact-property  DELETE /v1/projects/${projectId}/contact-properties/${propertyId}\n',
  );
  process.stdout.write('  contacts.list-contacts  GET /v1/projects/${projectId}/contacts\n');
  process.stdout.write(
    '  contacts.get-contact  GET /v1/projects/${projectId}/contacts/${contactId}\n',
  );
  process.stdout.write(
    '  contacts.list-contact-segments  GET /v1/projects/${projectId}/contacts/${contactId}/segments\n',
  );
  process.stdout.write(
    '  contacts.get-contact-topics  GET /v1/projects/${projectId}/contacts/${contactId}/topics\n',
  );
  process.stdout.write('  contacts.create-contact  POST /v1/projects/${projectId}/contacts\n');
  process.stdout.write(
    '  contacts.update-contact  PATCH /v1/projects/${projectId}/contacts/${contactId}\n',
  );
  process.stdout.write(
    '  contacts.delete-contact  DELETE /v1/projects/${projectId}/contacts/${contactId}\n',
  );
  process.stdout.write(
    '  contacts.upload-contact-image  POST /v1/projects/${projectId}/contacts/${contactId}/image\n',
  );
  process.stdout.write(
    '  contacts.set-contact-image-url  PUT /v1/projects/${projectId}/contacts/${contactId}/image\n',
  );
  process.stdout.write(
    '  contacts.delete-contact-image  DELETE /v1/projects/${projectId}/contacts/${contactId}/image\n',
  );
  process.stdout.write(
    '  contacts.add-contact-to-segment  POST /v1/projects/${projectId}/contacts/${contactId}/segments\n',
  );
  process.stdout.write(
    '  contacts.remove-contact-from-segment  DELETE /v1/projects/${projectId}/contacts/${contactId}/segments/${segmentId}\n',
  );
  process.stdout.write(
    '  contacts.update-contact-topics  PATCH /v1/projects/${projectId}/contacts/${contactId}/topics\n',
  );
  process.stdout.write(
    '  contacts.get-contact-activity  GET /v1/projects/${projectId}/contacts/${contactId}/activity\n',
  );
  process.stdout.write(
    '  contacts.get-contact-engagement-score  GET /v1/projects/${projectId}/contacts/${contactId}/engagement\n',
  );
  process.stdout.write(
    '  contacts.get-contact-email-validation-status  GET /v1/projects/${projectId}/contacts/${contactId}/email-validation\n',
  );
  process.stdout.write(
    '  contacts.refresh-contact-engagement-score  POST /v1/projects/${projectId}/contacts/${contactId}/engagement/refresh\n',
  );
  process.stdout.write(
    '  contacts.record-contact-email-validation  POST /v1/projects/${projectId}/contacts/${contactId}/email-validation\n',
  );
  process.stdout.write('  webhooks.list-webhooks  GET /v1/projects/${projectId}/webhooks\n');
  process.stdout.write(
    '  webhooks.get-webhook  GET /v1/projects/${projectId}/webhooks/${endpointId}\n',
  );
  process.stdout.write(
    '  webhooks.list-webhook-deliveries  GET /v1/projects/${projectId}/webhooks/${endpointId}/deliveries\n',
  );
  process.stdout.write(
    '  webhooks.get-webhook-delivery  GET /v1/projects/${projectId}/webhooks/${endpointId}/deliveries/${deliveryId}\n',
  );
  process.stdout.write('  webhooks.create-webhook  POST /v1/projects/${projectId}/webhooks\n');
  process.stdout.write(
    '  webhooks.update-webhook  PATCH /v1/projects/${projectId}/webhooks/${endpointId}\n',
  );
  process.stdout.write(
    '  webhooks.delete-webhook  DELETE /v1/projects/${projectId}/webhooks/${endpointId}\n',
  );
  process.stdout.write(
    '  webhooks.test-webhook  POST /v1/projects/${projectId}/webhooks/${endpointId}/test\n',
  );
  process.stdout.write(
    '  webhooks.replay-webhook-delivery  POST /v1/projects/${projectId}/webhooks/${endpointId}/replay/${deliveryId}\n',
  );
  process.stdout.write('  api-keys.list-api-keys  GET /v1/projects/${projectId}/api-keys\n');
  process.stdout.write('  api-keys.get-api-key  GET /v1/projects/${projectId}/api-keys/${keyId}\n');
  process.stdout.write(
    '  api-keys.get-api-key-usage  GET /v1/projects/${projectId}/api-keys/${keyId}/usage\n',
  );
  process.stdout.write(
    '  api-keys.export-api-key-usage  GET /v1/projects/${projectId}/api-keys/${keyId}/usage/export\n',
  );
  process.stdout.write('  projects.list-projects  GET /v1/projects\n');
  process.stdout.write('  projects.get-project  GET /v1/projects/${projectId}\n');
  process.stdout.write('  projects.update-project  PATCH /v1/projects/${projectId}\n');
  process.stdout.write('  projects.list-emails  GET /v1/projects/${projectId}/emails\n');
  process.stdout.write(
    '  projects.get-project-email  GET /v1/projects/${projectId}/emails/${emailId}\n',
  );
  process.stdout.write(
    '  projects.get-email-timeline  GET /v1/projects/${projectId}/emails/${emailId}/events\n',
  );
  process.stdout.write('  sending-domains.list-domains  GET /v1/projects/${projectId}/domains\n');
  process.stdout.write(
    '  sending-domains.get-domain  GET /v1/projects/${projectId}/domains/${domainId}\n',
  );
  process.stdout.write(
    '  sending-domains.register-domain  POST /v1/projects/${projectId}/domains\n',
  );
  process.stdout.write(
    '  sending-domains.verify-domain  POST /v1/projects/${projectId}/domains/${domainId}/verify\n',
  );
  process.stdout.write(
    '  sending-domains.delete-domain  DELETE /v1/projects/${projectId}/domains/${domainId}\n',
  );
  process.stdout.write(
    '  sending-domains.verify-bimi  POST /v1/projects/${projectId}/domains/${domainId}/bimi/verify\n',
  );
  process.stdout.write(
    '  sending-domains.update-bimi  PATCH /v1/projects/${projectId}/domains/${domainId}/bimi\n',
  );
  process.stdout.write(`\nOptions:\n`);
  process.stdout.write(`  --path name=value       Repeat for path parameters\n`);
  process.stdout.write(`  --body-json JSON        JSON request body (maximum 1 MiB)\n`);
  process.stdout.write(`  --query-json JSON       JSON query object\n`);
  process.stdout.write(`  --headers-json JSON     JSON operation headers\n`);
  process.stdout.write(`  --cookies-json JSON     JSON cookie values\n`);
  process.stdout.write(`  --base-url URL          Override the generated API URL\n`);
  process.stdout.write(`  --timeout-ms NUMBER     Positive request timeout\n`);
  process.stdout.write(`  --help                  Show this help\n`);
}

const secretValues = ([] as Array<string | undefined>).filter(
  (value): value is string => typeof value === 'string' && value.length > 0,
);

function safeError(error: unknown): { error: string; requestId?: string } {
  let message = error instanceof Error ? error.message : String(error);
  for (const secret of secretValues) message = message.replaceAll(secret, '[REDACTED]');
  const record =
    error && typeof error === 'object' ? (error as Record<string, unknown>) : undefined;
  const requestId = record?.requestId ?? record?.request_id;
  return typeof requestId === 'string' ? { error: message, requestId } : { error: message };
}

async function main(): Promise<void> {
  const args = parseCommandLine(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return;
  }
  if (!args.command) throw new Error('Missing command; use --help to list commands');

  const client = createApolloSignalApiClient({
    baseUrl: args.baseUrl,
    timeoutMs: args.timeoutMs,
  });
  const requestOptions = args.timeoutMs === undefined ? undefined : { timeoutMs: args.timeoutMs };
  let result: unknown;

  switch (args.command) {
    case 'emails.send-email': {
      const body = requireValue(args.body, '--body-json');
      result = client.emails.sendEmail(body as never, requestOptions);
      break;
    }
    case 'emails.get-email': {
      result = client.emails.getEmail(
        parsePathValue(requirePath(args.path, 'emailId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'emails.batch-send-emails': {
      const body = requireValue(args.body, '--body-json');
      result = client.emails.batchSendEmails(body as never, requestOptions);
      break;
    }
    case 'emails.cancel-email': {
      result = client.emails.cancelEmail(
        parsePathValue(requirePath(args.path, 'emailId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'emails.bulk-cancel-emails': {
      result = client.emails.bulkCancelEmails(requestOptions);
      break;
    }
    case 'emails.issue-stream-token': {
      result = client.emails.issueStreamToken(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'emails.stream-email-events': {
      result = client.emails.streamEmailEvents(requestOptions);
      break;
    }
    case 'emails.validate-links': {
      const body = requireValue(args.body, '--body-json');
      result = client.emails.validateLinks(body as never, requestOptions);
      break;
    }
    case 'metrics.get-topic-performance': {
      const query = args.query;
      result = client.metrics.getTopicPerformance(
        parsePathValue(requirePath(args.path, 'id'), 'string') as never,
        query as never,
        requestOptions,
      );
      break;
    }
    case 'metrics.get-email-performance': {
      result = client.metrics.getEmailPerformance(
        parsePathValue(requirePath(args.path, 'id'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'metrics.get-email-engagement': {
      result = client.metrics.getEmailEngagement(
        parsePathValue(requirePath(args.path, 'id'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'metrics.get-project-metrics-summary': {
      const query = args.query;
      result = client.metrics.getProjectMetricsSummary(query as never, requestOptions);
      break;
    }
    case 'metrics.get-project-metrics-timeline': {
      const query = args.query;
      result = client.metrics.getProjectMetricsTimeline(query as never, requestOptions);
      break;
    }
    case 'metrics.get-metrics-advisor': {
      const query = args.query;
      result = client.metrics.getMetricsAdvisor(query as never, requestOptions);
      break;
    }
    case 'suppressions.list-suppressions': {
      result = client.suppressions.listSuppressions(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'suppressions.export-suppressions': {
      result = client.suppressions.exportSuppressions(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'suppressions.add-suppression': {
      const body = requireValue(args.body, '--body-json');
      result = client.suppressions.addSuppression(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'suppressions.remove-suppression': {
      result = client.suppressions.removeSuppression(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'email'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'suppressions.import-suppressions': {
      const body = requireValue(args.body, '--body-json');
      result = client.suppressions.importSuppressions(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'segments.list-segments': {
      result = client.segments.listSegments(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'segments.get-segment': {
      result = client.segments.getSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'segmentId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'segments.list-contacts-in-segment': {
      result = client.segments.listContactsInSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'segmentId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'segments.create-segment': {
      const body = requireValue(args.body, '--body-json');
      result = client.segments.createSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'segments.delete-segment': {
      result = client.segments.deleteSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'segmentId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'topics.list-topics': {
      result = client.topics.listTopics(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'topics.get-topic': {
      result = client.topics.getTopic(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'topicId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'topics.list-contacts-in-topic': {
      result = client.topics.listContactsInTopic(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'topicId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'topics.create-topic': {
      const body = requireValue(args.body, '--body-json');
      result = client.topics.createTopic(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'topics.update-topic': {
      const body = requireValue(args.body, '--body-json');
      result = client.topics.updateTopic(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'topicId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'topics.delete-topic': {
      result = client.topics.deleteTopic(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'topicId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contact-properties.list-contact-properties': {
      result = client.contactProperties.listContactProperties(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contact-properties.get-contact-property': {
      result = client.contactProperties.getContactProperty(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'propertyId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contact-properties.create-contact-property': {
      const body = requireValue(args.body, '--body-json');
      result = client.contactProperties.createContactProperty(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contact-properties.update-contact-property': {
      const body = requireValue(args.body, '--body-json');
      result = client.contactProperties.updateContactProperty(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'propertyId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contact-properties.delete-contact-property': {
      result = client.contactProperties.deleteContactProperty(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'propertyId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.list-contacts': {
      result = client.contacts.listContacts(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.get-contact': {
      result = client.contacts.getContact(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.list-contact-segments': {
      result = client.contacts.listContactSegments(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.get-contact-topics': {
      result = client.contacts.getContactTopics(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.create-contact': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.createContact(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.update-contact': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.updateContact(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.delete-contact': {
      result = client.contacts.deleteContact(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.upload-contact-image': {
      result = client.contacts.uploadContactImage(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.set-contact-image-url': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.setContactImageUrl(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.delete-contact-image': {
      result = client.contacts.deleteContactImage(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.add-contact-to-segment': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.addContactToSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.remove-contact-from-segment': {
      result = client.contacts.removeContactFromSegment(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'segmentId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.update-contact-topics': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.updateContactTopics(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.get-contact-activity': {
      result = client.contacts.getContactActivity(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.get-contact-engagement-score': {
      result = client.contacts.getContactEngagementScore(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.get-contact-email-validation-status': {
      result = client.contacts.getContactEmailValidationStatus(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.refresh-contact-engagement-score': {
      result = client.contacts.refreshContactEngagementScore(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'contacts.record-contact-email-validation': {
      const body = requireValue(args.body, '--body-json');
      result = client.contacts.recordContactEmailValidation(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'contactId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.list-webhooks': {
      result = client.webhooks.listWebhooks(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.get-webhook': {
      result = client.webhooks.getWebhook(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.list-webhook-deliveries': {
      result = client.webhooks.listWebhookDeliveries(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.get-webhook-delivery': {
      result = client.webhooks.getWebhookDelivery(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'deliveryId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.create-webhook': {
      const body = requireValue(args.body, '--body-json');
      result = client.webhooks.createWebhook(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.update-webhook': {
      const body = requireValue(args.body, '--body-json');
      result = client.webhooks.updateWebhook(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.delete-webhook': {
      result = client.webhooks.deleteWebhook(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.test-webhook': {
      result = client.webhooks.testWebhook(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'webhooks.replay-webhook-delivery': {
      result = client.webhooks.replayWebhookDelivery(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'endpointId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'deliveryId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'api-keys.list-api-keys': {
      result = client.apiKeys.listApiKeys(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'api-keys.get-api-key': {
      result = client.apiKeys.getApiKey(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'keyId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'api-keys.get-api-key-usage': {
      result = client.apiKeys.getApiKeyUsage(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'keyId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'api-keys.export-api-key-usage': {
      result = client.apiKeys.exportApiKeyUsage(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'keyId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'projects.list-projects': {
      result = client.projects.listProjects(requestOptions);
      break;
    }
    case 'projects.get-project': {
      result = client.projects.getProject(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'projects.update-project': {
      const body = requireValue(args.body, '--body-json');
      result = client.projects.updateProject(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'projects.list-emails': {
      result = client.projects.listEmails(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'projects.get-project-email': {
      result = client.projects.getProjectEmail(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'emailId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'projects.get-email-timeline': {
      result = client.projects.getEmailTimeline(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'emailId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.list-domains': {
      result = client.sendingDomains.listDomains(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.get-domain': {
      result = client.sendingDomains.getDomain(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'domainId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.register-domain': {
      const body = requireValue(args.body, '--body-json');
      result = client.sendingDomains.registerDomain(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.verify-domain': {
      result = client.sendingDomains.verifyDomain(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'domainId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.delete-domain': {
      result = client.sendingDomains.deleteDomain(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'domainId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.verify-bimi': {
      result = client.sendingDomains.verifyBimi(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'domainId'), 'string') as never,
        requestOptions,
      );
      break;
    }
    case 'sending-domains.update-bimi': {
      const body = requireValue(args.body, '--body-json');
      result = client.sendingDomains.updateBimi(
        parsePathValue(requirePath(args.path, 'projectId'), 'string') as never,
        parsePathValue(requirePath(args.path, 'domainId'), 'string') as never,
        body as never,
        requestOptions,
      );
      break;
    }
    default:
      throw new Error(`Unknown command: ${args.command}`);
  }

  if (isAsyncIterable(result)) {
    for await (const event of result) printJson(event);
    return;
  }
  printJson(await result);
}

main().catch((error: unknown) => {
  process.stderr.write(`${JSON.stringify(safeError(error))}\n`);
  process.exitCode = 1;
});
