/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import { createTransport, type SDKTransport } from './transport/axios.js';
import { EmailsAPI } from './domain/emails.js';
import { MetricsAPI } from './domain/metrics.js';
import { SuppressionsAPI } from './domain/suppressions.js';
import { SegmentsAPI } from './domain/segments.js';
import { TopicsAPI } from './domain/topics.js';
import { ContactPropertiesAPI } from './domain/contact-properties.js';
import { ContactsAPI } from './domain/contacts.js';
import { WebhooksAPI } from './domain/webhooks.js';
import { ApiKeysAPI } from './domain/api-keys.js';
import { ProjectsAPI } from './domain/projects.js';
import { SendingDomainsAPI } from './domain/sending-domains.js';

/**
 * Apollo Signal API SDK client.
 *
 * @example
 * ```ts
 * import { ApolloSignalApi } from '@apollo-deploy/signal-sdk';
 *
 * const client = new ApolloSignalApi();
 * ```
 */
export class ApolloSignalApi {
  private readonly _transport: SDKTransport;

  /** EmailsAPI operations */
  readonly emails: EmailsAPI;
  /** MetricsAPI operations */
  readonly metrics: MetricsAPI;
  /** SuppressionsAPI operations */
  readonly suppressions: SuppressionsAPI;
  /** SegmentsAPI operations */
  readonly segments: SegmentsAPI;
  /** TopicsAPI operations */
  readonly topics: TopicsAPI;
  /** ContactPropertiesAPI operations */
  readonly contactProperties: ContactPropertiesAPI;
  /** ContactsAPI operations */
  readonly contacts: ContactsAPI;
  /** WebhooksAPI operations */
  readonly webhooks: WebhooksAPI;
  /** ApiKeysAPI operations */
  readonly apiKeys: ApiKeysAPI;
  /** ProjectsAPI operations */
  readonly projects: ProjectsAPI;
  /** SendingDomainsAPI operations */
  readonly sendingDomains: SendingDomainsAPI;

  constructor() {
    this._transport = createTransport({
      baseUrl: 'https://signal.apollodeploy.com',
      timeoutMs: 15000,
      retries: { attempts: 3, backoffMs: 400, jitter: true },
    });

    this.emails = new EmailsAPI(this._transport);
    this.metrics = new MetricsAPI(this._transport);
    this.suppressions = new SuppressionsAPI(this._transport);
    this.segments = new SegmentsAPI(this._transport);
    this.topics = new TopicsAPI(this._transport);
    this.contactProperties = new ContactPropertiesAPI(this._transport);
    this.contacts = new ContactsAPI(this._transport);
    this.webhooks = new WebhooksAPI(this._transport);
    this.apiKeys = new ApiKeysAPI(this._transport);
    this.projects = new ProjectsAPI(this._transport);
    this.sendingDomains = new SendingDomainsAPI(this._transport);
  }
}
