/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

// Client class — primary entry point
export { ApolloSignalApi } from './src/client.js';

// Domain classes
export { EmailsAPI } from './src/domain/emails.js';
export { MetricsAPI } from './src/domain/metrics.js';
export { SuppressionsAPI } from './src/domain/suppressions.js';
export { SegmentsAPI } from './src/domain/segments.js';
export { TopicsAPI } from './src/domain/topics.js';
export { ContactPropertiesAPI } from './src/domain/contact-properties.js';
export { ContactsAPI } from './src/domain/contacts.js';
export { WebhooksAPI } from './src/domain/webhooks.js';
export { ApiKeysAPI } from './src/domain/api-keys.js';
export { ProjectsAPI } from './src/domain/projects.js';
export { SendingDomainsAPI } from './src/domain/sending-domains.js';

// Error class
export { SDKError } from './src/types/errors.js';

// Common types
export type {
  PaginationQuery,
  PageMeta,
  Page,
  SuccessResponse,
  MessageResponse,
  ApiErrorEnvelope,
} from './src/types/common.js';
