// This file is auto-generated by Tesseract. Do not edit manually.
import { z } from 'zod';
import {
  ActivityResponseSchema,
  TopicSubscriptionResponseSchema,
  type ActivityResponse,
  type TopicSubscriptionResponse,
} from './models.js';
export const ListContactSegmentsResponseSchema = z
  .array(z.string())
  .meta({ id: 'ListContactSegmentsResponse' });
export type ListContactSegmentsResponse = z.infer<typeof ListContactSegmentsResponseSchema>;
export const GetContactTopicsResponseSchema = z
  .array(z.lazy(() => TopicSubscriptionResponseSchema))
  .meta({ id: 'GetContactTopicsResponse' });
export type GetContactTopicsResponse = z.infer<typeof GetContactTopicsResponseSchema>;
export const GetContactActivityResponseSchema = z
  .array(z.lazy(() => ActivityResponseSchema))
  .meta({ id: 'GetContactActivityResponse' });
export type GetContactActivityResponse = z.infer<typeof GetContactActivityResponseSchema>;
