// This file is auto-generated by Tesseract. Do not edit manually.
import { z } from 'zod';
export const AttachmentRequestSchema = z
  .object({
    filename: z.string(),
    content: z.string(),
    contentType: z.string(),
    disposition: z.string().optional(),
    contentId: z.string().nullable().optional(),
  })
  .meta({ id: 'AttachmentRequest' });
export type AttachmentRequest = z.infer<typeof AttachmentRequestSchema>;
export const DeliveryWindowRequestSchema = z
  .object({
    start: z.string(),
    end: z.string(),
  })
  .meta({ id: 'DeliveryWindowRequest' });
export type DeliveryWindowRequest = z.infer<typeof DeliveryWindowRequestSchema>;
export const TrackingSettingsRequestSchema = z
  .object({
    openTracking: z.boolean().nullable().optional(),
    clickTracking: z.boolean().nullable().optional(),
    unsubscribeTracking: z.boolean().nullable().optional(),
    readEngagement: z.boolean().nullable().optional(),
  })
  .meta({ id: 'TrackingSettingsRequest' });
export type TrackingSettingsRequest = z.infer<typeof TrackingSettingsRequestSchema>;
export const SendEmailRequestSchema = z
  .object({
    from: z.string(),
    to: z.array(z.string()),
    cc: z.array(z.string()).nullable().optional(),
    bcc: z.array(z.string()).nullable().optional(),
    replyTo: z.string().nullable().optional(),
    subject: z.string().nullable().optional(),
    html: z.string().nullable().optional(),
    text: z.string().nullable().optional(),
    tags: z.record(z.string(), z.string()).nullable().optional(),
    metadata: z.record(z.string(), z.string()).nullable().optional(),
    idempotencyKey: z.string().nullable().optional(),
    testMode: z.boolean().optional(),
    attachments: z
      .array(z.lazy(() => AttachmentRequestSchema))
      .nullable()
      .optional(),
    scheduledAt: z.string().nullable().optional(),
    deliveryWindow: z
      .lazy(() => DeliveryWindowRequestSchema)
      .nullable()
      .optional(),
    sendTimeCategory: z.string().optional(),
    trackingSettings: z
      .lazy(() => TrackingSettingsRequestSchema)
      .nullable()
      .optional(),
  })
  .meta({ id: 'SendEmailRequest' });
export type SendEmailRequest = z.infer<typeof SendEmailRequestSchema>;
export const BatchSendItemResponseSchema = z
  .object({
    index: z.number().int(),
    id: z.string().nullable().optional(),
    messageId: z.string().nullable().optional(),
    status: z.string().nullable().optional(),
    createdAt: z.string().nullable().optional(),
    scheduledAt: z.string().nullable().optional(),
    error: z.string().nullable().optional(),
  })
  .meta({ id: 'BatchSendItemResponse' });
export type BatchSendItemResponse = z.infer<typeof BatchSendItemResponseSchema>;
export const SendEmailResponseSchema = z
  .object({
    id: z.string(),
    messageId: z.string().nullable(),
    status: z.string(),
    createdAt: z.string(),
    scheduledAt: z.string().nullable().optional(),
    audienceId: z.string().nullable().optional(),
    messages: z
      .array(z.lazy(() => BatchSendItemResponseSchema))
      .nullable()
      .optional(),
  })
  .meta({ id: 'SendEmailResponse' });
export type SendEmailResponse = z.infer<typeof SendEmailResponseSchema>;
export const EmailDetailResponseSchema = z
  .object({
    id: z.string(),
    messageId: z.string().nullable(),
    from: z.string(),
    to: z.array(z.string()),
    cc: z.array(z.string()).nullable(),
    bcc: z.array(z.string()).nullable(),
    replyTo: z.string().nullable(),
    subject: z.string(),
    html: z.string().nullable().optional(),
    text: z.string().nullable().optional(),
    status: z.string(),
    error: z.string().nullable(),
    tags: z.record(z.string(), z.string()).nullable(),
    metadata: z.record(z.string(), z.string()).nullable(),
    testMode: z.boolean(),
    topicId: z.string().nullable().optional(),
    createdAt: z.string(),
    sentAt: z.string().nullable(),
    updatedAt: z.string().nullable(),
  })
  .meta({ id: 'EmailDetailResponse' });
export type EmailDetailResponse = z.infer<typeof EmailDetailResponseSchema>;
export const BatchSendRequestSchema = z
  .object({
    items: z.array(z.lazy(() => SendEmailRequestSchema)),
  })
  .meta({ id: 'BatchSendRequest' });
export type BatchSendRequest = z.infer<typeof BatchSendRequestSchema>;
export const BatchSendResponseSchema = z
  .object({
    results: z.array(z.lazy(() => BatchSendItemResponseSchema)),
  })
  .meta({ id: 'BatchSendResponse' });
export type BatchSendResponse = z.infer<typeof BatchSendResponseSchema>;
export const CancelResponseSchema = z
  .object({
    cancelled: z.boolean().optional(),
  })
  .meta({ id: 'CancelResponse' });
export type CancelResponse = z.infer<typeof CancelResponseSchema>;
export const BulkCancelResponseSchema = z
  .object({
    cancelled: z.number().int(),
  })
  .meta({ id: 'BulkCancelResponse' });
export type BulkCancelResponse = z.infer<typeof BulkCancelResponseSchema>;
export const StreamTokenResponseSchema = z
  .object({
    token: z.string(),
    expiresAt: z.string(),
  })
  .meta({ id: 'StreamTokenResponse' });
export type StreamTokenResponse = z.infer<typeof StreamTokenResponseSchema>;
export const StreamEventResponseSchema = z
  .object({
    type: z.string(),
    emailId: z.string(),
    occurredAt: z.string(),
    data: z.record(z.string(), z.string()).optional(),
  })
  .meta({ id: 'StreamEventResponse' });
export type StreamEventResponse = z.infer<typeof StreamEventResponseSchema>;
export const ValidateLinksRequestSchema = z
  .object({
    html: z.string().nullable().optional(),
  })
  .meta({ id: 'ValidateLinksRequest' });
export type ValidateLinksRequest = z.infer<typeof ValidateLinksRequestSchema>;
export const LinkResultItemSchema = z
  .object({
    url: z.string(),
    status: z.string(),
    statusCode: z.number().int().nullable().optional(),
    error: z.string().nullable().optional(),
  })
  .meta({ id: 'LinkResultItem' });
export type LinkResultItem = z.infer<typeof LinkResultItemSchema>;
export const ValidateLinksResponseSchema = z
  .object({
    links: z.array(z.lazy(() => LinkResultItemSchema)),
    totalLinks: z.number().int(),
    brokenLinks: z.number().int(),
    errorLinks: z.number().int(),
  })
  .meta({ id: 'ValidateLinksResponse' });
export type ValidateLinksResponse = z.infer<typeof ValidateLinksResponseSchema>;
export const MetricsWindowResponseSchema = z
  .object({
    from: z.string(),
    to: z.string(),
    label: z.string(),
  })
  .meta({ id: 'MetricsWindowResponse' });
export type MetricsWindowResponse = z.infer<typeof MetricsWindowResponseSchema>;
export const TopicPerformanceResponseSchema = z
  .object({
    topicId: z.string(),
    topicName: z.string(),
    window: z.lazy(() => MetricsWindowResponseSchema),
    totalEmails: z.number().int(),
    delivered: z.number().int(),
    deliveryRate: z.number(),
    opened: z.number().int(),
    openRate: z.number(),
    clicked: z.number().int(),
    clickRate: z.number(),
    bounced: z.number().int(),
    bounceRate: z.number(),
    complained: z.number().int(),
    complaintRate: z.number(),
    unsubscribed: z.number().int(),
    unsubscribeRate: z.number(),
    readEngaged: z.number().int(),
    readEngagementRate: z.number(),
    avgReadTimeSeconds: z.number().nullable(),
    optInCount: z.number().int(),
    optOutCount: z.number().int(),
    computedAt: z.string(),
  })
  .meta({ id: 'TopicPerformanceResponse' });
export type TopicPerformanceResponse = z.infer<typeof TopicPerformanceResponseSchema>;
export const EmailPerformanceResponseSchema = z
  .object({
    emailId: z.string(),
    subject: z.string(),
    fromAddress: z.string(),
    topicId: z.string().nullable(),
    status: z.string(),
    delivered: z.boolean(),
    opened: z.boolean(),
    clicked: z.boolean(),
    totalClicks: z.number().int(),
    bounced: z.boolean(),
    complained: z.boolean(),
    unsubscribed: z.boolean(),
    readEngaged: z.boolean(),
    readTimeSeconds: z.number().nullable(),
    readCategory: z.string().nullable(),
    sentAt: z.string().nullable(),
    lastEventAt: z.string().nullable(),
    computedAt: z.string(),
  })
  .meta({ id: 'EmailPerformanceResponse' });
export type EmailPerformanceResponse = z.infer<typeof EmailPerformanceResponseSchema>;
export const EmailReadScrollAnalyticsResponseSchema = z
  .object({
    emailId: z.string(),
    subject: z.string(),
    computedAt: z.string(),
    readEngaged: z.boolean(),
    readTimeSeconds: z.number().nullable(),
    readCategory: z.string().nullable(),
    mailClient: z.string().nullable(),
    deviceType: z.string().nullable(),
    os: z.string().nullable(),
    readEngagedAt: z.string().nullable(),
    shortEmail: z.boolean(),
    depth25Count: z.number().int(),
    depth50Count: z.number().int(),
    depth75Count: z.number().int(),
    depth100Count: z.number().int(),
    maxDepthPct: z.number().int().nullable(),
    depth25Rate: z.number().nullable(),
    depth50Rate: z.number().nullable(),
    depth75Rate: z.number().nullable(),
    depth100Rate: z.number().nullable(),
  })
  .meta({ id: 'EmailReadScrollAnalyticsResponse' });
export type EmailReadScrollAnalyticsResponse = z.infer<
  typeof EmailReadScrollAnalyticsResponseSchema
>;
export const ProjectMetricsSummaryResponseSchema = z
  .object({
    projectId: z.string(),
    window: z.lazy(() => MetricsWindowResponseSchema),
    sent: z.number().int(),
    delivered: z.number().int(),
    opened: z.number().int(),
    clicked: z.number().int(),
    bounced: z.number().int(),
    complained: z.number().int(),
    failed: z.number().int(),
    unsubscribed: z.number().int(),
    readEngaged: z.number().int(),
    deliveryRate: z.number(),
    openRate: z.number(),
    clickRate: z.number(),
    bounceRate: z.number(),
    complaintRate: z.number(),
    readEngagementRate: z.number(),
  })
  .meta({ id: 'ProjectMetricsSummaryResponse' });
export type ProjectMetricsSummaryResponse = z.infer<typeof ProjectMetricsSummaryResponseSchema>;
export const ProjectTimelineBucketResponseSchema = z
  .object({
    bucket: z.string(),
    type: z.string(),
    count: z.number().int(),
  })
  .meta({ id: 'ProjectTimelineBucketResponse' });
export type ProjectTimelineBucketResponse = z.infer<typeof ProjectTimelineBucketResponseSchema>;
export const ProjectMetricsTimelineResponseSchema = z
  .object({
    projectId: z.string(),
    window: z.lazy(() => MetricsWindowResponseSchema),
    granularity: z.string(),
    format: z.string(),
    buckets: z.array(z.lazy(() => ProjectTimelineBucketResponseSchema)),
  })
  .meta({ id: 'ProjectMetricsTimelineResponse' });
export type ProjectMetricsTimelineResponse = z.infer<typeof ProjectMetricsTimelineResponseSchema>;
export const AdvisorRecommendationDataResponseSchema = z
  .object({
    bounceRate: z.number().nullable().optional(),
    bounced: z.number().int().nullable().optional(),
    accepted: z.number().int().nullable().optional(),
    complaintRate: z.number().nullable().optional(),
    accepted24h: z.number().int().nullable().optional(),
    avgDailyAccepted7d: z.number().int().nullable().optional(),
    daysSinceLastSend: z.number().int().nullable().optional(),
    reportedOpenRate: z.number().nullable().optional(),
    adjustedOpenRate: z.number().nullable().optional(),
    proxyRate: z.number().nullable().optional(),
    proxyOpens: z.number().int().nullable().optional(),
    totalOpens: z.number().int().nullable().optional(),
    humanOpenRate: z.number().nullable().optional(),
    delivered: z.number().int().nullable().optional(),
    unsubRate: z.number().nullable().optional(),
    unsubscribed: z.number().int().nullable().optional(),
    dmarcAlignmentFailureRate7d: z.number().nullable().optional(),
    dmarcDomain: z.string().nullable().optional(),
    dmarcCurrentPolicy: z.string().nullable().optional(),
    dmarcRecommendedPolicy: z.string().nullable().optional(),
    dmarcObservedMessages: z.number().int().nullable().optional(),
    dmarcAlignedMessages: z.number().int().nullable().optional(),
    dmarcAccountedRate: z.number().nullable().optional(),
    dmarcUnknownMessages: z.number().int().nullable().optional(),
    dmarcUnknownSources: z.number().int().nullable().optional(),
    dmarcReportingDays: z.number().int().nullable().optional(),
  })
  .meta({ id: 'AdvisorRecommendationDataResponse' });
export type AdvisorRecommendationDataResponse = z.infer<
  typeof AdvisorRecommendationDataResponseSchema
>;
export const AdvisorRecommendationResponseSchema = z
  .object({
    code: z.string(),
    severity: z.string(),
    title: z.string(),
    message: z.string(),
    data: z
      .lazy(() => AdvisorRecommendationDataResponseSchema)
      .nullable()
      .optional(),
  })
  .meta({ id: 'AdvisorRecommendationResponse' });
export type AdvisorRecommendationResponse = z.infer<typeof AdvisorRecommendationResponseSchema>;
export const AdvisorReportResponseSchema = z
  .object({
    projectId: z.string(),
    generatedAt: z.string(),
    score: z.number().int(),
    recommendations: z.array(z.lazy(() => AdvisorRecommendationResponseSchema)),
  })
  .meta({ id: 'AdvisorReportResponse' });
export type AdvisorReportResponse = z.infer<typeof AdvisorReportResponseSchema>;
export const SuppressionResponseSchema = z
  .object({
    id: z.string(),
    projectId: z.string(),
    email: z.string(),
    reason: z.string(),
    createdAt: z.string(),
    contactId: z.string().nullable().optional(),
  })
  .meta({ id: 'SuppressionResponse' });
export type SuppressionResponse = z.infer<typeof SuppressionResponseSchema>;
export const PageInfoSchema = z
  .object({
    page: z.number().int(),
    size: z.number().int(),
    total: z.number().int(),
    totalPages: z.number().int(),
    hasNextPage: z.boolean(),
    hasPreviousPage: z.boolean(),
  })
  .meta({ id: 'PageInfo' });
export type PageInfo = z.infer<typeof PageInfoSchema>;
export const SuppressionPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => SuppressionResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'SuppressionPageResponse' });
export type SuppressionPageResponse = z.infer<typeof SuppressionPageResponseSchema>;
export const AddSuppressionBodySchema = z
  .object({
    email: z.string(),
  })
  .meta({ id: 'AddSuppressionBody' });
export type AddSuppressionBody = z.infer<typeof AddSuppressionBodySchema>;
export const SuppressionImportRowSerializableSchema = z
  .object({
    email: z.string(),
    reason: z.string().nullable().optional(),
  })
  .meta({ id: 'SuppressionImportRowSerializable' });
export type SuppressionImportRowSerializable = z.infer<
  typeof SuppressionImportRowSerializableSchema
>;
export const SuppressionImportBodySchema = z
  .object({
    suppressions: z.array(z.lazy(() => SuppressionImportRowSerializableSchema)),
  })
  .meta({ id: 'SuppressionImportBody' });
export type SuppressionImportBody = z.infer<typeof SuppressionImportBodySchema>;
export const SuppressionImportResponseSchema = z
  .object({
    imported: z.number().int(),
    skipped: z.number().int(),
  })
  .meta({ id: 'SuppressionImportResponse' });
export type SuppressionImportResponse = z.infer<typeof SuppressionImportResponseSchema>;
export const SegmentResponseSchema = z
  .object({
    object: z.string().optional(),
    id: z.string(),
    name: z.string(),
    projectId: z.string(),
    createdAt: z.string(),
    contactCount: z.number().int().optional(),
    unsubscribedCount: z.number().int().optional(),
  })
  .meta({ id: 'SegmentResponse' });
export type SegmentResponse = z.infer<typeof SegmentResponseSchema>;
export const SegmentPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => SegmentResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'SegmentPageResponse' });
export type SegmentPageResponse = z.infer<typeof SegmentPageResponseSchema>;
export const SegmentContactResponseSchema = z
  .object({
    contactId: z.string(),
    email: z.string(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    segments: z.array(z.string()),
  })
  .meta({ id: 'SegmentContactResponse' });
export type SegmentContactResponse = z.infer<typeof SegmentContactResponseSchema>;
export const CursorInfoSchema = z
  .object({
    nextCursor: z.string().nullable(),
    previousCursor: z.string().nullable(),
    hasNextPage: z.boolean(),
    hasPreviousPage: z.boolean(),
  })
  .meta({ id: 'CursorInfo' });
export type CursorInfo = z.infer<typeof CursorInfoSchema>;
export const CursorPageSchema = z
  .object({
    data: z.array(z.lazy(() => SegmentContactResponseSchema)),
    cursor: z.lazy(() => CursorInfoSchema),
  })
  .meta({ id: 'CursorPage' });
export type CursorPage = z.infer<typeof CursorPageSchema>;
export const CreateSegmentBodySchema = z
  .object({
    name: z.string(),
  })
  .meta({ id: 'CreateSegmentBody' });
export type CreateSegmentBody = z.infer<typeof CreateSegmentBodySchema>;
export const TopicResponseSchema = z
  .object({
    object: z.string().optional(),
    id: z.string(),
    name: z.string(),
    defaultSubscription: z.string(),
    description: z.string().nullable(),
    visibility: z.string(),
    projectId: z.string(),
    optInCount: z.number().int(),
    optOutCount: z.number().int(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'TopicResponse' });
export type TopicResponse = z.infer<typeof TopicResponseSchema>;
export const TopicPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => TopicResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'TopicPageResponse' });
export type TopicPageResponse = z.infer<typeof TopicPageResponseSchema>;
export const CreateTopicBodySchema = z
  .object({
    name: z.string(),
    defaultSubscription: z.string(),
    description: z.string().nullable().optional(),
    visibility: z.string().nullable().optional(),
  })
  .meta({ id: 'CreateTopicBody' });
export type CreateTopicBody = z.infer<typeof CreateTopicBodySchema>;
export const UpdateTopicBodySchema = z
  .object({
    name: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    visibility: z.string().nullable().optional(),
  })
  .meta({ id: 'UpdateTopicBody' });
export type UpdateTopicBody = z.infer<typeof UpdateTopicBodySchema>;
export const ContactPropertyResponseSchema = z
  .object({
    object: z.string().optional(),
    id: z.string(),
    key: z.string(),
    type: z.string(),
    fallbackValue: z.string().nullable(),
    projectId: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'ContactPropertyResponse' });
export type ContactPropertyResponse = z.infer<typeof ContactPropertyResponseSchema>;
export const ContactPropertyPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => ContactPropertyResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'ContactPropertyPageResponse' });
export type ContactPropertyPageResponse = z.infer<typeof ContactPropertyPageResponseSchema>;
export const CreateContactPropertyBodySchema = z
  .object({
    key: z.string(),
    type: z.string(),
    fallbackValue: z.string().nullable().optional(),
  })
  .meta({ id: 'CreateContactPropertyBody' });
export type CreateContactPropertyBody = z.infer<typeof CreateContactPropertyBodySchema>;
export const UpdateContactPropertyBodySchema = z
  .object({
    fallbackValue: z.string().nullable().optional(),
  })
  .meta({ id: 'UpdateContactPropertyBody' });
export type UpdateContactPropertyBody = z.infer<typeof UpdateContactPropertyBodySchema>;
export const TopicSubscriptionResponseSchema = z
  .object({
    topicId: z.string(),
    subscription: z.string(),
  })
  .meta({ id: 'TopicSubscriptionResponse' });
export type TopicSubscriptionResponse = z.infer<typeof TopicSubscriptionResponseSchema>;
export const ContactResponseSchema = z
  .object({
    object: z.string().optional(),
    id: z.string(),
    email: z.string(),
    phone: z.string().nullable().optional(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    unsubscribed: z.boolean(),
    properties: z.record(z.string(), z.string()),
    profileImageUrl: z.string().nullable(),
    projectId: z.string(),
    segments: z.array(z.string()),
    topics: z.array(z.lazy(() => TopicSubscriptionResponseSchema)),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'ContactResponse' });
export type ContactResponse = z.infer<typeof ContactResponseSchema>;
export const ContactPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => ContactResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'ContactPageResponse' });
export type ContactPageResponse = z.infer<typeof ContactPageResponseSchema>;
export const SegmentRefSchema = z
  .object({
    id: z.string(),
  })
  .meta({ id: 'SegmentRef' });
export type SegmentRef = z.infer<typeof SegmentRefSchema>;
export const TopicSubscriptionBodySchema = z
  .object({
    id: z.string(),
    subscription: z.string(),
  })
  .meta({ id: 'TopicSubscriptionBody' });
export type TopicSubscriptionBody = z.infer<typeof TopicSubscriptionBodySchema>;
export const CreateContactBodySchema = z
  .object({
    email: z.string(),
    phone: z.string().nullable().optional(),
    firstName: z.string().nullable().optional(),
    lastName: z.string().nullable().optional(),
    unsubscribed: z.boolean().optional(),
    properties: z.record(z.string(), z.string()).optional(),
    segments: z.array(z.lazy(() => SegmentRefSchema)).optional(),
    topics: z.array(z.lazy(() => TopicSubscriptionBodySchema)).optional(),
  })
  .meta({ id: 'CreateContactBody' });
export type CreateContactBody = z.infer<typeof CreateContactBodySchema>;
export const UpdateContactBodySchema = z
  .object({
    firstName: z.string().nullable().optional(),
    lastName: z.string().nullable().optional(),
    phone: z.string().nullable().optional(),
    unsubscribed: z.boolean().nullable().optional(),
    properties: z.record(z.string(), z.string()).nullable().optional(),
  })
  .meta({ id: 'UpdateContactBody' });
export type UpdateContactBody = z.infer<typeof UpdateContactBodySchema>;
export const SetImageUrlBodySchema = z
  .object({
    url: z.string(),
  })
  .meta({ id: 'SetImageUrlBody' });
export type SetImageUrlBody = z.infer<typeof SetImageUrlBodySchema>;
export const AddToSegmentBodySchema = z
  .object({
    segmentId: z.string(),
  })
  .meta({ id: 'AddToSegmentBody' });
export type AddToSegmentBody = z.infer<typeof AddToSegmentBodySchema>;
export const UpdateTopicsBodySchema = z
  .object({
    topics: z.array(z.lazy(() => TopicSubscriptionBodySchema)),
  })
  .meta({ id: 'UpdateTopicsBody' });
export type UpdateTopicsBody = z.infer<typeof UpdateTopicsBodySchema>;
export const ActivityMetadataResponseSchema = z
  .object({
    topicId: z.string().nullable().optional(),
  })
  .meta({ id: 'ActivityMetadataResponse' });
export type ActivityMetadataResponse = z.infer<typeof ActivityMetadataResponseSchema>;
export const ActivityResponseSchema = z
  .object({
    object: z.string().optional(),
    id: z.string(),
    type: z.string(),
    referenceId: z.string().nullable().optional(),
    referenceName: z.string().nullable().optional(),
    metadata: z
      .lazy(() => ActivityMetadataResponseSchema)
      .nullable()
      .optional(),
    occurredAt: z.string(),
  })
  .meta({ id: 'ActivityResponse' });
export type ActivityResponse = z.infer<typeof ActivityResponseSchema>;
export const EngagementScoreResponseSchema = z
  .object({
    object: z.string().optional(),
    score: z.number().int(),
    tier: z.string(),
    scoredAt: z.string(),
  })
  .meta({ id: 'EngagementScoreResponse' });
export type EngagementScoreResponse = z.infer<typeof EngagementScoreResponseSchema>;
export const EmailValidationStatusResponseSchema = z
  .object({
    object: z.string().optional(),
    status: z.string(),
    reason: z.string().nullable(),
    validatedAt: z.string().nullable(),
  })
  .meta({ id: 'EmailValidationStatusResponse' });
export type EmailValidationStatusResponse = z.infer<typeof EmailValidationStatusResponseSchema>;
export const RecordValidationBodySchema = z
  .object({
    status: z.lazy(() => EmailValidationStatusInputSchema),
    reason: z.string().nullable().optional(),
  })
  .meta({ id: 'RecordValidationBody' });
export type RecordValidationBody = z.infer<typeof RecordValidationBodySchema>;
export const WebhookFilterSerializableSchema = z
  .object({
    field: z.string(),
    operator: z.string(),
    value: z.string().nullable().optional(),
  })
  .meta({ id: 'WebhookFilterSerializable' });
export type WebhookFilterSerializable = z.infer<typeof WebhookFilterSerializableSchema>;
export const WebhookTransformationSerializableSchema = z
  .object({
    type: z.string(),
    from: z.string().nullable().optional(),
    to: z.string().nullable().optional(),
    field: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
    template: z.string().nullable().optional(),
  })
  .meta({ id: 'WebhookTransformationSerializable' });
export type WebhookTransformationSerializable = z.infer<
  typeof WebhookTransformationSerializableSchema
>;
export const WebhookResponseSchema = z
  .object({
    id: z.string(),
    projectId: z.string(),
    name: z.string(),
    url: z.string(),
    events: z.array(z.string()),
    enabled: z.boolean(),
    filters: z.array(z.lazy(() => WebhookFilterSerializableSchema)).nullable(),
    transformations: z.array(z.lazy(() => WebhookTransformationSerializableSchema)).nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'WebhookResponse' });
export type WebhookResponse = z.infer<typeof WebhookResponseSchema>;
export const WebhookPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => WebhookResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'WebhookPageResponse' });
export type WebhookPageResponse = z.infer<typeof WebhookPageResponseSchema>;
export const WebhookDeliveryResponseSchema = z
  .object({
    id: z.string(),
    projectId: z.string(),
    webhookEndpointId: z.string(),
    eventType: z.string(),
    status: z.string(),
    attemptCount: z.number().int(),
    lastStatusCode: z.number().int().nullable(),
    lastError: z.string().nullable(),
    responseBodySnippet: z.string().nullable(),
    nextAttemptAt: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'WebhookDeliveryResponse' });
export type WebhookDeliveryResponse = z.infer<typeof WebhookDeliveryResponseSchema>;
export const WebhookDeliveryPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => WebhookDeliveryResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'WebhookDeliveryPageResponse' });
export type WebhookDeliveryPageResponse = z.infer<typeof WebhookDeliveryPageResponseSchema>;
export const CreateWebhookBodySchema = z
  .object({
    url: z.string(),
    events: z.array(z.string()),
    name: z.string().nullable().optional(),
    secret: z.string().nullable().optional(),
    filters: z
      .array(z.lazy(() => WebhookFilterSerializableSchema))
      .nullable()
      .optional(),
    transformations: z
      .array(z.lazy(() => WebhookTransformationSerializableSchema))
      .nullable()
      .optional(),
  })
  .meta({ id: 'CreateWebhookBody' });
export type CreateWebhookBody = z.infer<typeof CreateWebhookBodySchema>;
export const WebhookCreateResponseSchema = z
  .object({
    id: z.string(),
    projectId: z.string(),
    name: z.string(),
    url: z.string(),
    events: z.array(z.string()),
    enabled: z.boolean(),
    filters: z.array(z.lazy(() => WebhookFilterSerializableSchema)).nullable(),
    transformations: z.array(z.lazy(() => WebhookTransformationSerializableSchema)).nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    secret: z.string(),
  })
  .meta({ id: 'WebhookCreateResponse' });
export type WebhookCreateResponse = z.infer<typeof WebhookCreateResponseSchema>;
export const UpdateWebhookBodySchema = z
  .object({
    name: z.string().nullable().optional(),
    url: z.string().nullable().optional(),
    events: z.array(z.string()).nullable().optional(),
    secret: z.string().nullable().optional(),
    enabled: z.boolean().nullable().optional(),
    filters: z
      .array(z.lazy(() => WebhookFilterSerializableSchema))
      .nullable()
      .optional(),
    transformations: z
      .array(z.lazy(() => WebhookTransformationSerializableSchema))
      .nullable()
      .optional(),
  })
  .meta({ id: 'UpdateWebhookBody' });
export type UpdateWebhookBody = z.infer<typeof UpdateWebhookBodySchema>;
export const ApiKeySchema = z
  .object({
    id: z.string(),
    configId: z.string(),
    name: z.string().nullable(),
    start: z.string().nullable(),
    prefix: z.string().nullable(),
    organizationId: z.string(),
    projectId: z.string().nullable(),
    enabled: z.boolean(),
    rateLimitEnabled: z.boolean(),
    rateLimitTimeWindow: z.number().int().nullable(),
    rateLimitMax: z.number().int().nullable(),
    requestCount: z.number().int(),
    remaining: z.number().int().nullable(),
    lastRequest: z.string().nullable(),
    expiresAt: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    metadata: z.record(z.string(), z.string()).nullable(),
    permissions: z.record(z.string(), z.array(z.string())).nullable(),
  })
  .meta({ id: 'ApiKey' });
export type ApiKey = z.infer<typeof ApiKeySchema>;
export const ApiKeyUsageRecordSchema = z
  .object({
    id: z.string(),
    keyId: z.string(),
    orgId: z.string(),
    method: z.string(),
    route: z.string(),
    statusCode: z.number().int(),
    durationMs: z.number().int().nullable(),
    ip: z.string().nullable(),
    ts: z.string(),
  })
  .meta({ id: 'ApiKeyUsageRecord' });
export type ApiKeyUsageRecord = z.infer<typeof ApiKeyUsageRecordSchema>;
export const UsagePageSchema = z
  .object({
    size: z.number().int(),
    totalPages: z.number().int(),
    hasMore: z.boolean(),
  })
  .meta({ id: 'UsagePage' });
export type UsagePage = z.infer<typeof UsagePageSchema>;
export const ApiKeyUsageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => ApiKeyUsageRecordSchema)),
    page: z.lazy(() => UsagePageSchema),
  })
  .meta({ id: 'ApiKeyUsageResponse' });
export type ApiKeyUsageResponse = z.infer<typeof ApiKeyUsageResponseSchema>;
export const ProjectLimitsModelSchema = z
  .object({
    dailySends: z.number().int(),
    perSecondSends: z.number().int(),
    maxRecipientsPerMessage: z.number().int(),
    maxDomains: z.number().int(),
    maxApiKeys: z.number().int(),
    maxWebhooks: z.number().int(),
  })
  .meta({ id: 'ProjectLimitsModel' });
export type ProjectLimitsModel = z.infer<typeof ProjectLimitsModelSchema>;
export const ProjectTrackingSettingsModelSchema = z
  .object({
    openTracking: z.boolean(),
    clickTracking: z.boolean(),
    unsubscribeTracking: z.boolean(),
    readEngagement: z.boolean(),
    scrollDepth: z.boolean().optional(),
  })
  .meta({ id: 'ProjectTrackingSettingsModel' });
export type ProjectTrackingSettingsModel = z.infer<typeof ProjectTrackingSettingsModelSchema>;
export const ProjectResponseSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    slug: z.string(),
    status: z.string(),
    suspensionReason: z.string().nullable(),
    region: z.string(),
    limits: z.lazy(() => ProjectLimitsModelSchema),
    trackingSettings: z.lazy(() => ProjectTrackingSettingsModelSchema),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'ProjectResponse' });
export type ProjectResponse = z.infer<typeof ProjectResponseSchema>;
export const ProjectPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => ProjectResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'ProjectPageResponse' });
export type ProjectPageResponse = z.infer<typeof ProjectPageResponseSchema>;
export const UpdateProjectRequestSchema = z
  .object({
    name: z.string().nullable().optional(),
    slug: z.string().nullable().optional(),
    limits: z
      .lazy(() => ProjectLimitsModelSchema)
      .nullable()
      .optional(),
    trackingSettings: z
      .lazy(() => ProjectTrackingSettingsModelSchema)
      .nullable()
      .optional(),
  })
  .meta({ id: 'UpdateProjectRequest' });
export type UpdateProjectRequest = z.infer<typeof UpdateProjectRequestSchema>;
export const EmailPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => EmailDetailResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'EmailPageResponse' });
export type EmailPageResponse = z.infer<typeof EmailPageResponseSchema>;
export const EmailTimelineItemSchema = z
  .object({
    id: z.string(),
    type: z.string(),
    providerEventId: z.string().nullable(),
    payload: z.record(z.string(), z.string().nullable()).nullable(),
    occurredAt: z.string(),
    createdAt: z.string(),
  })
  .meta({ id: 'EmailTimelineItem' });
export type EmailTimelineItem = z.infer<typeof EmailTimelineItemSchema>;
export const EmailTimelineResponseSchema = z
  .object({
    items: z.array(z.lazy(() => EmailTimelineItemSchema)),
  })
  .meta({ id: 'EmailTimelineResponse' });
export type EmailTimelineResponse = z.infer<typeof EmailTimelineResponseSchema>;
export const DomainListItemResponseSchema = z
  .object({
    id: z.string(),
    domain: z.string(),
    region: z.string(),
    status: z.string(),
    dkimStatus: z.string(),
    bimiStatus: z.string(),
    trackingStatus: z.string(),
    updatedAt: z.string(),
  })
  .meta({ id: 'DomainListItemResponse' });
export type DomainListItemResponse = z.infer<typeof DomainListItemResponseSchema>;
export const DomainListPageResponseSchema = z
  .object({
    data: z.array(z.lazy(() => DomainListItemResponseSchema)),
    page: z.lazy(() => PageInfoSchema),
  })
  .meta({ id: 'DomainListPageResponse' });
export type DomainListPageResponse = z.infer<typeof DomainListPageResponseSchema>;
export const DkimRecordResponseSchema = z
  .object({
    name: z.string(),
    type: z.string(),
    value: z.string(),
    status: z.string().nullable().optional(),
  })
  .meta({ id: 'DkimRecordResponse' });
export type DkimRecordResponse = z.infer<typeof DkimRecordResponseSchema>;
export const DnsRecordResponseSchema = z
  .object({
    name: z.string(),
    type: z.string(),
    value: z.string(),
    priority: z.number().int().nullable().optional(),
    optional: z.boolean().nullable().optional(),
    status: z.string().nullable().optional(),
  })
  .meta({ id: 'DnsRecordResponse' });
export type DnsRecordResponse = z.infer<typeof DnsRecordResponseSchema>;
export const VerificationRecordsResponseSchema = z
  .object({
    dkim: z.array(z.lazy(() => DkimRecordResponseSchema)),
    mailFromMx: z.lazy(() => DnsRecordResponseSchema),
    mailFromSpf: z.lazy(() => DnsRecordResponseSchema),
    dmarcRecommended: z
      .lazy(() => DnsRecordResponseSchema)
      .nullable()
      .optional(),
    bimi: z
      .lazy(() => DnsRecordResponseSchema)
      .nullable()
      .optional(),
    trackingCname: z
      .lazy(() => DnsRecordResponseSchema)
      .nullable()
      .optional(),
  })
  .meta({ id: 'VerificationRecordsResponse' });
export type VerificationRecordsResponse = z.infer<typeof VerificationRecordsResponseSchema>;
export const DomainResponseSchema = z
  .object({
    id: z.string(),
    projectId: z.string(),
    domain: z.string(),
    region: z.string(),
    status: z.string(),
    dkimStatus: z.string(),
    spfStatus: z.string(),
    dmarcStatus: z.string(),
    mailFromStatus: z.string(),
    mailFromDomain: z.string(),
    verificationRecords: z.lazy(() => VerificationRecordsResponseSchema),
    bimiStatus: z.string(),
    bimiLogoUrl: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    verifiedAt: z.string().nullable(),
  })
  .meta({ id: 'DomainResponse' });
export type DomainResponse = z.infer<typeof DomainResponseSchema>;
export const RegisterDomainRequestSchema = z
  .object({
    domain: z.string(),
    region: z.string(),
  })
  .meta({ id: 'RegisterDomainRequest' });
export type RegisterDomainRequest = z.infer<typeof RegisterDomainRequestSchema>;
export const UpdateBimiRequestSchema = z
  .object({
    logoUrl: z.string().nullable().optional(),
  })
  .meta({ id: 'UpdateBimiRequest' });
export type UpdateBimiRequest = z.infer<typeof UpdateBimiRequestSchema>;
export const EmailValidationStatusInputSchema = z
  .enum(['valid', 'risky', 'invalid', 'unknown'])
  .meta({ id: 'EmailValidationStatusInput' });
export type EmailValidationStatusInput = z.infer<typeof EmailValidationStatusInputSchema>;
