/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import type { SDKTransport, RequestOptions } from '../transport/axios.js';
import type {
  AdvisorReportResponse,
  EmailPerformanceResponse,
  EmailReadScrollAnalyticsResponse,
  GetMetricsAdvisorQuery,
  GetProjectMetricsSummaryQuery,
  GetProjectMetricsTimelineQuery,
  GetTopicPerformanceQuery,
  ProjectMetricsSummaryResponse,
  ProjectMetricsTimelineResponse,
  TopicPerformanceResponse,
} from '../types/index.js';

export interface MetricsAPI {
  getTopicPerformance(
    id: string,
    query?: GetTopicPerformanceQuery,
    options?: RequestOptions,
  ): Promise<TopicPerformanceResponse>;

  getEmailPerformance(id: string, options?: RequestOptions): Promise<EmailPerformanceResponse>;

  getEmailEngagement(
    id: string,
    options?: RequestOptions,
  ): Promise<EmailReadScrollAnalyticsResponse>;

  getProjectMetricsSummary(
    query?: GetProjectMetricsSummaryQuery,
    options?: RequestOptions,
  ): Promise<ProjectMetricsSummaryResponse>;

  getProjectMetricsTimeline(
    query?: GetProjectMetricsTimelineQuery,
    options?: RequestOptions,
  ): Promise<ProjectMetricsTimelineResponse>;

  getMetricsAdvisor(
    query?: GetMetricsAdvisorQuery,
    options?: RequestOptions,
  ): Promise<AdvisorReportResponse>;
}

export function createMetricsAPI(transport: SDKTransport): MetricsAPI {
  return {
    getTopicPerformance(
      id: string,
      query?: GetTopicPerformanceQuery,
      options?: RequestOptions,
    ): Promise<TopicPerformanceResponse> {
      const params = query
        ? {
            window: query['window'],
            projectId: query['projectId'],
          }
        : undefined;
      return transport.executeRequest<TopicPerformanceResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/topics/${encodeURIComponent(String(id))}`,
          params,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getEmailPerformance(id: string, options?: RequestOptions): Promise<EmailPerformanceResponse> {
      return transport.executeRequest<EmailPerformanceResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/emails/${encodeURIComponent(String(id))}`,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getEmailEngagement(
      id: string,
      options?: RequestOptions,
    ): Promise<EmailReadScrollAnalyticsResponse> {
      return transport.executeRequest<EmailReadScrollAnalyticsResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/emails/${encodeURIComponent(String(id))}/engagement`,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getProjectMetricsSummary(
      query?: GetProjectMetricsSummaryQuery,
      options?: RequestOptions,
    ): Promise<ProjectMetricsSummaryResponse> {
      const params = query
        ? {
            window: query['window'],
            projectId: query['projectId'],
          }
        : undefined;
      return transport.executeRequest<ProjectMetricsSummaryResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/summary`,
          params,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getProjectMetricsTimeline(
      query?: GetProjectMetricsTimelineQuery,
      options?: RequestOptions,
    ): Promise<ProjectMetricsTimelineResponse> {
      const params = query
        ? {
            window: query['window'],
            granularity: query['granularity'],
            format: query['format'],
            projectId: query['projectId'],
          }
        : undefined;
      return transport.executeRequest<ProjectMetricsTimelineResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/timeline`,
          params,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getMetricsAdvisor(
      query?: GetMetricsAdvisorQuery,
      options?: RequestOptions,
    ): Promise<AdvisorReportResponse> {
      const params = query
        ? {
            projectId: query['projectId'],
          }
        : undefined;
      return transport.executeRequest<AdvisorReportResponse>(
        {
          method: 'GET',
          url: `/v1/metrics/advisor`,
          params,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },
  };
}
