// This file is auto-generated by Tesseract. Do not edit manually.
import { z } from 'zod';
import { ApiKeySchema, type ApiKey } from './models.js';
export const ListApiKeysResponseSchema = z
  .object({})
  .catchall(z.array(z.lazy(() => ApiKeySchema)))
  .meta({ id: 'ListApiKeysResponse' });
export type ListApiKeysResponse = z.infer<typeof ListApiKeysResponseSchema>;
