// This file is auto-generated by Tesseract. Do not edit manually.
import { z } from 'zod';
export const GetTopicPerformanceQuerySchema = z
  .object({
    window: z.string().optional().describe('Time window.'),
    projectId: z
      .string()
      .optional()
      .describe('Required for session auth; ignored for API key auth.'),
  })
  .meta({ id: 'GetTopicPerformanceQuery' });
export type GetTopicPerformanceQuery = z.infer<typeof GetTopicPerformanceQuerySchema>;
export const GetProjectMetricsSummaryQuerySchema = z
  .object({
    window: z.string().optional().describe('Metrics time window.'),
    projectId: z
      .string()
      .optional()
      .describe('Required for session auth; ignored for API key auth.'),
  })
  .meta({ id: 'GetProjectMetricsSummaryQuery' });
export type GetProjectMetricsSummaryQuery = z.infer<typeof GetProjectMetricsSummaryQuerySchema>;
export const GetProjectMetricsTimelineQuerySchema = z
  .object({
    window: z.string().optional().describe('Metrics time window.'),
    granularity: z.string().optional().describe('`hour` or `day`.'),
    format: z.string().optional().describe('`compact` or `detailed`.'),
    projectId: z
      .string()
      .optional()
      .describe('Required for session auth; ignored for API key auth.'),
  })
  .meta({ id: 'GetProjectMetricsTimelineQuery' });
export type GetProjectMetricsTimelineQuery = z.infer<typeof GetProjectMetricsTimelineQuerySchema>;
export const GetMetricsAdvisorQuerySchema = z
  .object({
    projectId: z
      .string()
      .optional()
      .describe('Required for session auth; ignored for API key auth.'),
  })
  .meta({ id: 'GetMetricsAdvisorQuery' });
export type GetMetricsAdvisorQuery = z.infer<typeof GetMetricsAdvisorQuerySchema>;
