/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import type { SDKTransport, RequestOptions } from '../transport/axios.js';
import type { ApiKey, ApiKeyUsageResponse, ListApiKeysResponse } from '../types/index.js';

export class ApiKeysAPI {
  constructor(private readonly _transport: SDKTransport) {}

  listApiKeys(projectId: string, options?: RequestOptions): Promise<ListApiKeysResponse> {
    return this._transport.executeRequest<ListApiKeysResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/api-keys`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  getApiKey(projectId: string, keyId: string, options?: RequestOptions): Promise<ApiKey> {
    return this._transport.executeRequest<ApiKey>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/api-keys/${encodeURIComponent(String(keyId))}`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  getApiKeyUsage(
    projectId: string,
    keyId: string,
    options?: RequestOptions,
  ): Promise<ApiKeyUsageResponse> {
    return this._transport.executeRequest<ApiKeyUsageResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/api-keys/${encodeURIComponent(String(keyId))}/usage`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  exportApiKeyUsage(projectId: string, keyId: string, options?: RequestOptions): Promise<void> {
    return this._transport.executeRequest<void>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/api-keys/${encodeURIComponent(String(keyId))}/usage/export`,
      },
      options,
      { mode: 'none' },
    );
  }
}
