/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import type { SDKTransport, RequestOptions } from '../transport/axios.js';
import { buildSDKUrl, claimSecurityHeader } from '../transport/axios.js';
import {
  createSSEDataStream,
  createSSEStream,
  type SSEEvent,
  type SSEOptions,
  type SSEClientConfig,
} from '../transport/sse.js';
import type {
  BatchSendRequest,
  BatchSendResponse,
  BulkCancelResponse,
  CancelResponse,
  EmailDetailResponse,
  SendEmailRequest,
  SendEmailResponse,
  StreamEventResponse,
  StreamTokenResponse,
  ValidateLinksRequest,
  ValidateLinksResponse,
} from '../types/index.js';

export interface EmailsAPI {
  sendEmail(input: SendEmailRequest, options?: RequestOptions): Promise<SendEmailResponse>;

  getEmail(emailId: string, options?: RequestOptions): Promise<EmailDetailResponse>;

  batchSendEmails(input: BatchSendRequest, options?: RequestOptions): Promise<BatchSendResponse>;

  cancelEmail(emailId: string, options?: RequestOptions): Promise<CancelResponse>;

  bulkCancelEmails(options?: RequestOptions): Promise<BulkCancelResponse>;

  issueStreamToken(projectId: string, options?: RequestOptions): Promise<StreamTokenResponse>;

  streamEmailEvents(options?: SSEOptions): AsyncIterable<SSEEvent<StreamEventResponse>>;

  validateLinks(
    input: ValidateLinksRequest,
    options?: RequestOptions,
  ): Promise<ValidateLinksResponse>;
}

export function createEmailsAPI(transport: SDKTransport): EmailsAPI {
  const __buildSSEClientConfig = (): SSEClientConfig => {
    const headers: Record<string, string> = {
      ...(transport.config.defaultHeaders ?? {}),
    };
    const query: Record<string, string> = {};
    const cookies: Record<string, string> = {
      ...(transport.config.cookies ?? {}),
    };
    const claimedSecurityHeaders = new Set<string>();
    return {
      headers: Object.keys(headers).length > 0 ? headers : undefined,
      query: Object.keys(query).length > 0 ? query : undefined,
      cookies: Object.keys(cookies).length > 0 ? cookies : undefined,
      withCredentials: transport.config.withCredentials,
    };
  };
  return {
    sendEmail(input: SendEmailRequest, options?: RequestOptions): Promise<SendEmailResponse> {
      return transport.executeRequest<SendEmailResponse>(
        {
          method: 'POST',
          url: `/v1/emails`,
          data: input,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    getEmail(emailId: string, options?: RequestOptions): Promise<EmailDetailResponse> {
      return transport.executeRequest<EmailDetailResponse>(
        {
          method: 'GET',
          url: `/v1/emails/${encodeURIComponent(String(emailId))}`,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    batchSendEmails(input: BatchSendRequest, options?: RequestOptions): Promise<BatchSendResponse> {
      return transport.executeRequest<BatchSendResponse>(
        {
          method: 'POST',
          url: `/v1/emails/batch`,
          data: input,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    cancelEmail(emailId: string, options?: RequestOptions): Promise<CancelResponse> {
      const requestHeaders: Record<string, string> = {};
      requestHeaders['Content-Type'] = 'application/json';
      return transport.executeRequest<CancelResponse>(
        {
          method: 'DELETE',
          url: `/v1/emails/${encodeURIComponent(String(emailId))}`,
          data: {},
          headers: Object.keys(requestHeaders).length > 0 ? requestHeaders : undefined,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    bulkCancelEmails(options?: RequestOptions): Promise<BulkCancelResponse> {
      const requestHeaders: Record<string, string> = {};
      requestHeaders['Content-Type'] = 'application/json';
      return transport.executeRequest<BulkCancelResponse>(
        {
          method: 'DELETE',
          url: `/v1/emails`,
          data: {},
          headers: Object.keys(requestHeaders).length > 0 ? requestHeaders : undefined,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    issueStreamToken(projectId: string, options?: RequestOptions): Promise<StreamTokenResponse> {
      const requestHeaders: Record<string, string> = {};
      requestHeaders['Content-Type'] = 'application/json';
      return transport.executeRequest<StreamTokenResponse>(
        {
          method: 'POST',
          url: `/v1/emails/${encodeURIComponent(String(projectId))}/stream/token`,
          data: {},
          headers: Object.keys(requestHeaders).length > 0 ? requestHeaders : undefined,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },

    streamEmailEvents(options?: SSEOptions): AsyncIterable<SSEEvent<StreamEventResponse>> {
      const sseUrl = buildSDKUrl(transport.config.baseUrl, `/v1/emails/stream`);
      return createSSEStream<StreamEventResponse>(
        sseUrl.toString(),
        {
          method: 'GET',
        },
        undefined,
        __buildSSEClientConfig(),
        options,
      );
    },

    validateLinks(
      input: ValidateLinksRequest,
      options?: RequestOptions,
    ): Promise<ValidateLinksResponse> {
      return transport.executeRequest<ValidateLinksResponse>(
        {
          method: 'POST',
          url: `/v1/emails/validate`,
          data: input,
        },
        options,
        { mode: 'required', allowEmptyString: false, allowNull: false },
      );
    },
  };
}
