/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import type { SDKTransport, RequestOptions } from '../transport/axios.js';
import type {
  EmailDetailResponse,
  EmailPageResponse,
  EmailTimelineResponse,
  ProjectPageResponse,
  ProjectResponse,
  UpdateProjectRequest,
} from '../types/index.js';

export class ProjectsAPI {
  constructor(private readonly _transport: SDKTransport) {}

  listProjects(options?: RequestOptions): Promise<ProjectPageResponse> {
    return this._transport.executeRequest<ProjectPageResponse>(
      {
        method: 'GET',
        url: `/v1/projects`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  getProject(projectId: string, options?: RequestOptions): Promise<ProjectResponse> {
    return this._transport.executeRequest<ProjectResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  updateProject(
    projectId: string,
    input: UpdateProjectRequest,
    options?: RequestOptions,
  ): Promise<ProjectResponse> {
    return this._transport.executeRequest<ProjectResponse>(
      {
        method: 'PATCH',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}`,
        data: input,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  listEmails(projectId: string, options?: RequestOptions): Promise<EmailPageResponse> {
    return this._transport.executeRequest<EmailPageResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/emails`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  getProjectEmail(
    projectId: string,
    emailId: string,
    options?: RequestOptions,
  ): Promise<EmailDetailResponse> {
    return this._transport.executeRequest<EmailDetailResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/emails/${encodeURIComponent(String(emailId))}`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  getEmailTimeline(
    projectId: string,
    emailId: string,
    options?: RequestOptions,
  ): Promise<EmailTimelineResponse> {
    return this._transport.executeRequest<EmailTimelineResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/emails/${encodeURIComponent(String(emailId))}/events`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }
}
