/**
 * @generated
 * This file was automatically generated by Tesseract.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 */

import type { SDKTransport, RequestOptions } from '../transport/axios.js';
import type {
  AddSuppressionBody,
  SuppressionImportBody,
  SuppressionImportResponse,
  SuppressionPageResponse,
  SuppressionResponse,
} from '../types/index.js';

export class SuppressionsAPI {
  constructor(private readonly _transport: SDKTransport) {}

  listSuppressions(projectId: string, options?: RequestOptions): Promise<SuppressionPageResponse> {
    return this._transport.executeRequest<SuppressionPageResponse>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/suppressions`,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  exportSuppressions(projectId: string, options?: RequestOptions): Promise<void> {
    return this._transport.executeRequest<void>(
      {
        method: 'GET',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/suppressions/export`,
      },
      options,
      { mode: 'none' },
    );
  }

  addSuppression(
    projectId: string,
    input: AddSuppressionBody,
    options?: RequestOptions,
  ): Promise<SuppressionResponse> {
    return this._transport.executeRequest<SuppressionResponse>(
      {
        method: 'POST',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/suppressions`,
        data: input,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }

  removeSuppression(projectId: string, email: string, options?: RequestOptions): Promise<void> {
    const requestHeaders: Record<string, string> = {};
    requestHeaders['Content-Type'] = 'application/json';
    return this._transport.executeRequest<void>(
      {
        method: 'DELETE',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/suppressions/${encodeURIComponent(String(email))}`,
        data: {},
        headers: Object.keys(requestHeaders).length > 0 ? requestHeaders : undefined,
      },
      options,
      { mode: 'none' },
    );
  }

  importSuppressions(
    projectId: string,
    input: SuppressionImportBody,
    options?: RequestOptions,
  ): Promise<SuppressionImportResponse> {
    return this._transport.executeRequest<SuppressionImportResponse>(
      {
        method: 'POST',
        url: `/v1/projects/${encodeURIComponent(String(projectId))}/suppressions/import`,
        data: input,
      },
      options,
      { mode: 'required', allowEmptyString: false, allowNull: false },
    );
  }
}
